import { existsSync } from 'fs'
import { cp, mkdir, readFile, rm } from 'fs/promises'
import { dirname, join, relative } from 'path'
import type {
  AgentConfigPreparationResult,
  IntegrationDiagnostic,
  McpServerConfig,
  SkillDescriptor
} from '../../../shared/integrations'
import type { AgentTypeId } from '../../../shared/settings'
import type { SettingsStore } from '../../settings/SettingsStore'
import { getGeneratedAgentConfigRoot } from '../../data/paths'
import { McpRegistry } from '../mcp/McpRegistry'
import { SkillsRegistry } from '../skills/SkillsRegistry'
import { getProjectMousseMcpConfigPath, getProjectMousseSkillRoot } from '../nativePaths'
import type { IntegrationActor } from '../../../shared/integrations/actor'
import type { EffectiveAgentGrants } from '../../../shared/agents/types'
import { resolveEffectiveMcpServers, resolveEffectiveSkills } from '../catalog/EffectiveIntegrationResolver'
import { shortHash } from '../revision'
import { atomicWriteFile } from '../atomicWrite'
import { assertOwnedPath } from '../../profiles/pathSafety'

const MOUSSE_MARKER = 'Generated by Mousse for an ephemeral agent worktree.'

type CleanupAction =
  | { kind: 'skill'; path: string }
  | { kind: 'config'; path: string; before: string | null; written: string }

interface CleanupRecord {
  worktreePath: string
  paths: string[]
  entries: CleanupAction[]
}

export class AgentConfigManager {
  private cleanupByAgent = new Map<string, CleanupRecord>()
  private readonly generatedConfigRoot?: string

  constructor(
    private mcpRegistry: McpRegistry,
    private skillsRegistry: SkillsRegistry,
    private settingsStore: SettingsStore,
    options: { generatedConfigRoot?: string } = {}
  ) {
    this.generatedConfigRoot = options.generatedConfigRoot
  }

  async prepare(
    agentId: string,
    cliType: AgentTypeId,
    worktreePath: string,
    projectPath: string,
    actor?: IntegrationActor
  ): Promise<AgentConfigPreparationResult> {
    await this.cleanup(agentId)
    const settings = this.settingsStore.get().integrations
    const effectiveActor = actor ?? { kind: 'agent' as const, agentType: cliType }
    const result: AgentConfigPreparationResult = {
      agentId,
      cliType,
      generatedFiles: [],
      cleanupPaths: [],
      env: {},
      warnings: [],
      logs: [],
      unsupportedCapabilities: []
    }
    const cleanup: CleanupRecord = { worktreePath, paths: [], entries: [] }

    if (settings.mcp.enabled && settings.mcp.enableForAgents[cliType]) {
      const servers = await this.getSelectedMcpServers(projectPath, effectiveActor)
      await this.materializeMcp(cliType, worktreePath, servers, result, cleanup)
    }

    if (settings.skills.enabled && settings.skills.enableForAgents[cliType]) {
      const skills = await this.getSelectedSkills(projectPath, effectiveActor)
      await this.materializeSkills(cliType, worktreePath, skills, result, cleanup)
    }

    if (cleanup.paths.length > 0) {
      this.cleanupByAgent.set(agentId, cleanup)
    }

    return result
  }

  /**
   * Materialize the immutable grants already resolved for one execution.
   * This intentionally bypasses mutable profile enablement toggles: the
   * resolver has already produced the pinned grant set for this run.
   */
  async prepareExact(
    agentId: string,
    cliType: AgentTypeId,
    worktreePath: string,
    projectPath: string,
    grants: EffectiveAgentGrants
  ): Promise<AgentConfigPreparationResult> {
    await this.cleanup(agentId)
    const result: AgentConfigPreparationResult = {
      agentId,
      cliType,
      generatedFiles: [],
      cleanupPaths: [],
      env: {},
      warnings: [],
      logs: [],
      unsupportedCapabilities: []
    }
    const cleanup: CleanupRecord = { worktreePath, paths: [], entries: [] }
    const [skillsSnapshot, mcpSnapshot] = await Promise.all([
      this.skillsRegistry.discover({ projectPath }),
      this.mcpRegistry.discover({ projectPath, redactSecrets: false })
    ])
    const skills = grants.skills.flatMap((grant) => {
      const skill = skillsSnapshot.skills.find((entry) =>
        entry.id === grant.id || entry.installationId === grant.id
      )
      if (!skill) {
        result.unsupportedCapabilities.push({ level: 'error', source: 'agent-materialization', targetId: grant.id, message: `Pinned skill grant is no longer installed: ${grant.id}` })
        return []
      }
      if ((grant.revision && grant.revision !== skill.revision) || (grant.hash && grant.hash !== skill.contentHash)) {
        result.unsupportedCapabilities.push({ level: 'error', source: 'agent-materialization', targetId: grant.id, message: `Pinned skill grant changed before execution: ${grant.id}` })
        return []
      }
      return [skill]
    })
    const serverIds = [...new Set(grants.mcpTools.map((grant) => grant.serverId))]
    const servers = serverIds.flatMap((serverId) => {
      const server = mcpSnapshot.servers.find((entry) => entry.id === serverId || entry.installationId === serverId)
      if (!server) {
        result.unsupportedCapabilities.push({ level: 'error', source: 'agent-materialization', targetId: serverId, message: `Pinned MCP server grant is no longer configured: ${serverId}` })
        return []
      }
      const serverGrants = grants.mcpTools.filter((grant) => grant.serverId === serverId)
      const changed = serverGrants.some((grant) =>
        (grant.revision && grant.revision !== server.configRevision) ||
        (grant.hash && grant.hash !== server.configRevision)
      )
      if (changed) {
        result.unsupportedCapabilities.push({ level: 'error', source: 'agent-materialization', targetId: serverId, message: `Pinned MCP configuration changed before execution: ${serverId}` })
        return []
      }
      return [{ ...server, enabledTools: serverGrants.map((grant) => grant.toolName) }]
    })
    if (servers.length > 0) await this.materializeMcp(cliType, worktreePath, servers, result, cleanup)
    if (skills.length > 0) await this.materializeSkills(cliType, worktreePath, skills, result, cleanup)
    if (cleanup.paths.length > 0) this.cleanupByAgent.set(agentId, cleanup)
    return result
  }

  async cleanup(agentId: string): Promise<string[]> {
    const cleanup = this.cleanupByAgent.get(agentId)
    const logs: string[] = []
    if (!cleanup) return logs

    for (const path of cleanup.paths) {
      // Cleanup is recursive, so never trust a remembered path without checking it again.
      // A malformed skill name or stale record must not escape the isolated worktree.
      let ownedPath: string
      try {
        ownedPath = assertOwnedPath(cleanup.worktreePath, path, 'agent integration cleanup')
      } catch {
        logs.push(`[integrations] Refused cleanup outside agent worktree: ${path}`)
        continue
      }
      let removed = false
      for (const action of cleanup.entries.filter((entry) => entry.path === path)) {
        if (action.kind === 'skill') {
          await rm(ownedPath, { recursive: true, force: true }).catch(() => {})
          removed = true
        } else {
          removed ||= await restoreOwnedConfig({ ...action, path: ownedPath })
        }
      }
      logs.push(removed
        ? `[integrations] Removed generated entries from ${path}`
        : `[integrations] Preserved config changed after materialization: ${path}`)
    }
    this.cleanupByAgent.delete(agentId)
    return logs
  }

  private async getSelectedMcpServers(
    projectPath: string,
    actor: IntegrationActor
  ): Promise<McpServerConfig[]> {
    const snapshot = await this.mcpRegistry.discover({ projectPath, redactSecrets: false })
    return resolveEffectiveMcpServers({
      servers: snapshot.servers,
      settings: this.settingsStore.get().integrations.mcp,
      actor
    })
  }

  private async getSelectedSkills(
    projectPath: string,
    actor: IntegrationActor
  ): Promise<SkillDescriptor[]> {
    const snapshot = await this.skillsRegistry.discover({ projectPath })
    return resolveEffectiveSkills({
      snapshot,
      settings: this.settingsStore.get().integrations.skills,
      actor
    })
  }

  private async materializeMcp(
    cliType: AgentTypeId,
    worktreePath: string,
    servers: McpServerConfig[],
    result: AgentConfigPreparationResult,
    cleanup: CleanupRecord
  ): Promise<void> {
    if (servers.length === 0) return
    const target = assertOwnedPath(worktreePath, getMcpTarget(cliType, worktreePath), 'agent MCP config')
    result.unsupportedCapabilities.push(...unsupportedMcpCapabilities(cliType, servers))
    const generated = prepareGeneratedMcpConfig(servers)
    Object.assign(result.env, generated.env)
    await mkdir(dirname(target), { recursive: true })
    if (cliType === 'codex') {
      const existed = existsSync(target)
      const existing = existed ? await readFile(target, 'utf-8') : ''
      const names = uniqueMaterializedNames(servers, existing, 'toml')
      const renamed = generated.servers.map((server, index) => ({ ...server, name: names[index]! }))
      const rendered = renderCodexToml(renamed)
      const written = existing.trim() ? `${existing.trimEnd()}\n\n${rendered}` : rendered
      await atomicWriteFile(target, written)
      addCleanupAction(result, cleanup, { kind: 'config', path: target, before: existed ? existing : null, written })
    } else {
      const field = cliType === 'opencode' ? 'mcp' : 'mcpServers'
      const existed = existsSync(target)
      const existing = existed ? await readFile(target, 'utf-8') : ''
      let document: Record<string, unknown> = {}
      if (existing.trim()) {
        try {
          const parsed = JSON.parse(existing) as unknown
          if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) throw new Error('root must be an object')
          document = parsed as Record<string, unknown>
        } catch (error) {
          const diagnostic = unsupportedDiagnostic(
            `Cannot materialize ${cliType} MCP config without rewriting an unreadable existing file: ${error instanceof Error ? error.message : String(error)}`,
            target
          )
          result.unsupportedCapabilities.push(diagnostic)
          result.warnings.push(diagnostic.message)
          return
        }
      }
      const existingEntries = document[field]
      if (existingEntries !== undefined && (!existingEntries || typeof existingEntries !== 'object' || Array.isArray(existingEntries))) {
        const diagnostic = unsupportedDiagnostic(`Cannot materialize ${cliType} MCP config because ${field} is not an object.`, target)
        result.unsupportedCapabilities.push(diagnostic)
        result.warnings.push(diagnostic.message)
        return
      }
      const entries = existingEntries && typeof existingEntries === 'object' && !Array.isArray(existingEntries)
        ? { ...(existingEntries as Record<string, unknown>) }
        : {}
      const names = uniqueMaterializedNames(servers, Object.keys(entries), 'json')
      const safeServers = generated.servers.map((server, index) => ({ ...server, name: names[index]! }))
      for (let index = 0; index < safeServers.length; index += 1) {
        entries[names[index]!] = renderMcpEntry(cliType, safeServers[index]!)
      }
      document[field] = entries
      const markerField = cliType === 'opencode' ? '$comment' : '_comment'
      if (!existed && typeof document[markerField] !== 'string') document[markerField] = MOUSSE_MARKER
      const written = `${JSON.stringify(document, null, 2)}\n`
      await atomicWriteFile(target, written)
      addCleanupAction(result, cleanup, { kind: 'config', path: target, before: existed ? existing : null, written })
    }
    result.logs.push(`[integrations] Materialized ${servers.length} resolved MCP server${servers.length === 1 ? '' : 's'} for ${cliType}`)
  }

  private async materializeSkills(
    cliType: AgentTypeId,
    worktreePath: string,
    skills: SkillDescriptor[],
    result: AgentConfigPreparationResult,
    cleanup: CleanupRecord
  ): Promise<void> {
    if (skills.length === 0) return
    const roots = getSkillTargets(cliType, worktreePath)

    for (const skill of skills) {
      for (const root of roots) {
        const target = join(root, skill.name)
        if (!isInside(target, worktreePath)) {
          result.warnings.push(
            `[integrations] Refused skill path outside agent worktree: ${skill.name}`
          )
          continue
        }
        if (isInside(skill.rootPath, worktreePath)) continue
        const destination = existsSync(target)
          ? `${target}__mousse_${shortHash(skill.installationId ?? skill.id)}`
          : target
        if (existsSync(target)) {
          result.warnings.push(`[integrations] Preserved existing skill ${relative(worktreePath, target)}; materialized the resolved skill at ${relative(worktreePath, destination)}`)
        }
        const ownedDestination = assertOwnedPath(worktreePath, destination, 'agent skill destination')
        await mkdir(dirname(ownedDestination), { recursive: true })
        await cp(skill.rootPath, ownedDestination, { recursive: true })
        result.generatedFiles.push(ownedDestination)
        addCleanupAction(result, cleanup, { kind: 'skill', path: ownedDestination })
      }
    }

    if (skills.length > 0) {
      result.logs.push(`[integrations] Materialized ${skills.length} skill folder${skills.length === 1 ? '' : 's'} for ${cliType}`)
    }
  }
}

export function getMcpTarget(cliType: AgentTypeId, worktreePath: string): string {
  switch (cliType) {
    case 'claude-code':
      return join(worktreePath, '.mcp.json')
    case 'codex':
      return join(worktreePath, '.codex', 'config.toml')
    case 'opencode':
      return join(worktreePath, 'opencode.json')
    case 'cursor-agents-cli':
      return join(worktreePath, '.cursor', 'mcp.json')
    case 'mousse':
      return getProjectMousseMcpConfigPath(worktreePath)
  }
}

export function getSkillTargets(cliType: AgentTypeId, worktreePath: string): string[] {
  switch (cliType) {
    case 'claude-code':
      return [join(worktreePath, '.claude', 'skills'), join(worktreePath, '.agents', 'skills')]
    case 'codex':
      return [join(worktreePath, '.codex', 'skills'), join(worktreePath, '.agents', 'skills')]
    case 'opencode':
      return [join(worktreePath, '.opencode', 'skills')]
    case 'cursor-agents-cli':
      return [join(worktreePath, '.cursor', 'skills'), join(worktreePath, '.agents', 'skills')]
    case 'mousse':
      return [getProjectMousseSkillRoot(worktreePath)]
  }
}

export function renderMcpConfig(cliType: AgentTypeId, servers: McpServerConfig[]): string {
  const safeServers = prepareGeneratedMcpConfig(servers).servers
  switch (cliType) {
    case 'claude-code':
    case 'cursor-agents-cli':
      return `${JSON.stringify({ _comment: MOUSSE_MARKER, mcpServers: renderCursorLikeServers(safeServers) }, null, 2)}\n`
    case 'codex':
      return renderCodexToml(safeServers)
    case 'opencode':
      return `${JSON.stringify({ $comment: MOUSSE_MARKER, mcp: renderOpenCodeServers(safeServers) }, null, 2)}\n`
    case 'mousse':
      return `${JSON.stringify({ _comment: MOUSSE_MARKER, mcpServers: renderCursorLikeServers(safeServers) }, null, 2)}\n`
  }
}

function renderCursorLikeServers(servers: McpServerConfig[]): Record<string, unknown> {
  return Object.fromEntries(
    servers.map((server) => [
      server.name,
      server.transport === 'stdio'
        ? compactObject({
            command: server.command,
            args: server.args,
            env: server.env,
            cwd: server.cwd
          })
        : compactObject({
            url: server.url,
            headers: server.headers,
            transport: server.transport
          })
    ])
  )
}

function renderOpenCodeServers(servers: McpServerConfig[]): Record<string, unknown> {
  return Object.fromEntries(
    servers.map((server) => [
      server.name,
      server.transport === 'stdio'
        ? compactObject({
            type: 'local',
            command: [server.command, ...(server.args ?? [])].filter(Boolean),
            environment: server.env,
            enabled: true
          })
        : compactObject({
            type: 'remote',
            url: server.url,
            headers: server.headers,
            enabled: true
          })
    ])
  )
}

function renderCodexToml(servers: McpServerConfig[]): string {
  const lines = [`# ${MOUSSE_MARKER}`]
  for (const server of servers) {
    lines.push('', `[mcp_servers.${quoteTomlKey(server.name)}]`)
    if (server.command) lines.push(`command = ${tomlValue(server.command)}`)
    if (server.args?.length) lines.push(`args = ${tomlValue(server.args)}`)
    if (server.env && Object.keys(server.env).length > 0) {
      lines.push(`env = ${tomlValue(server.env)}`)
    }
    if (server.cwd) lines.push(`cwd = ${tomlValue(server.cwd)}`)
    if (server.url) lines.push(`url = ${tomlValue(server.url)}`)
    if (server.headers && Object.keys(server.headers).length > 0) {
      lines.push(`http_headers = ${tomlValue(server.headers)}`)
    }
    lines.push('enabled = true')
  }
  return `${lines.join('\n')}\n`
}

function compactObject(value: Record<string, unknown>): Record<string, unknown> {
  return Object.fromEntries(
    Object.entries(value).filter(([, entry]) => entry !== undefined && entry !== null)
  )
}

function tomlValue(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(tomlValue).join(', ')}]`
  if (value && typeof value === 'object') {
    return `{ ${Object.entries(value as Record<string, unknown>)
      .map(([key, entry]) => `${quoteTomlKey(key)} = ${tomlValue(entry)}`)
      .join(', ')} }`
  }
  if (typeof value === 'boolean') return value ? 'true' : 'false'
  return JSON.stringify(String(value))
}

function quoteTomlKey(key: string): string {
  return /^[A-Za-z0-9_-]+$/.test(key) ? key : JSON.stringify(key)
}

function isInside(child: string, parent: string): boolean {
  const rel = relative(parent, child)
  return Boolean(rel) && !rel.startsWith('..') && !rel.startsWith('/')
}

export function prepareGeneratedMcpConfig(servers: McpServerConfig[]): {
  servers: McpServerConfig[]
  env: Record<string, string>
} {
  // Sort independently of discovery order so generated names stay stable across runs.
  const entries = servers
    .flatMap((server) => [
      ...Object.entries(server.env ?? {}).map(([key, value]) => ({
        server, field: 'env' as const, key, value, base: toEnvName(key)
      })),
      ...Object.entries(server.headers ?? {}).map(([key, value]) => ({
        server, field: 'headers' as const, key, value,
        base: `MCP_${toEnvName(server.name)}_${toEnvName(key)}`
      }))
    ])
    .filter((entry) => !containsEnvReference(entry.value))
    .sort((a, b) => `${a.base}\0${a.server.id}\0${a.field}\0${a.key}`.localeCompare(
      `${b.base}\0${b.server.id}\0${b.field}\0${b.key}`
    ))

  const byBase = new Map<string, typeof entries>()
  for (const entry of entries) {
    const group = byBase.get(entry.base) ?? []
    group.push(entry)
    byBase.set(entry.base, group)
  }
  const env: Record<string, string> = {}
  const names = new Map<string, string>()
  for (const entry of entries) {
    const group = byBase.get(entry.base) ?? []
    // A shared key with the same value can safely use one variable. Different values
    // are namespaced by source/server, preventing one selected server leaking into another.
    const conflict = new Set(group.map((candidate) => candidate.value)).size > 1
    const name = conflict
      ? `${entry.base}_${toEnvName(entry.server.source)}_${toEnvName(entry.server.name)}`
      : entry.base
    const uniqueName = env[name] === undefined || env[name] === entry.value
      ? name
      : `${name}_${createStableSuffix(entry.server.id, entry.key)}`
    env[uniqueName] = entry.value
    names.set(entryKey(entry.server, entry.field, entry.key), uniqueName)
  }

  return {
    env,
    servers: servers.map((server) => ({
      ...server,
      env: replaceLiteralSecrets(server, 'env', server.env, names),
      headers: replaceLiteralSecrets(server, 'headers', server.headers, names)
    }))
  }
}

function replaceLiteralSecrets(
  server: McpServerConfig,
  field: 'env' | 'headers',
  record: Record<string, string> | undefined,
  names: Map<string, string>
): Record<string, string> | undefined {
  if (!record) return undefined
  return Object.fromEntries(Object.entries(record).map(([key, value]) => [
    key,
    containsEnvReference(value) ? value : `\${env:${names.get(entryKey(server, field, key))!}}`
  ]))
}

function entryKey(server: McpServerConfig, field: string, key: string): string {
  return `${server.id}\0${field}\0${key}`
}

function createStableSuffix(serverId: string, key: string): string {
  let hash = 0
  for (const char of `${serverId}:${key}`) hash = ((hash * 31) + char.charCodeAt(0)) >>> 0
  return hash.toString(36).toUpperCase()
}

function containsEnvReference(value: string): boolean {
  return (
    /\$\{env:[A-Za-z_][A-Za-z0-9_]*}/.test(value) ||
    /\$\{[A-Za-z_][A-Za-z0-9_]*}/.test(value) ||
    /(^|[^A-Za-z0-9_])\$[A-Za-z_][A-Za-z0-9_]*/.test(value) ||
    /%[A-Za-z_][A-Za-z0-9_]*%/.test(value)
  )
}

function addCleanupAction(
  result: AgentConfigPreparationResult,
  cleanup: CleanupRecord,
  action: CleanupAction
): void {
  cleanup.entries.push(action)
  if (!cleanup.paths.includes(action.path)) cleanup.paths.push(action.path)
  if (!result.cleanupPaths.includes(action.path)) result.cleanupPaths.push(action.path)
  if (!result.generatedFiles.includes(action.path)) result.generatedFiles.push(action.path)
}

function unsupportedDiagnostic(message: string, path?: string, targetId?: string): IntegrationDiagnostic {
  return { level: 'warning', message, path, targetId, source: 'agent-materialization' }
}

function unsupportedMcpCapabilities(cliType: AgentTypeId, servers: McpServerConfig[]): IntegrationDiagnostic[] {
  const diagnostics: IntegrationDiagnostic[] = []
  for (const server of servers) {
    if (server.authMode === 'oauth' && cliType !== 'mousse') {
      diagnostics.push(unsupportedDiagnostic(
        `${cliType} materialization preserves the MCP endpoint but cannot materialize an OAuth session; connect through Mousse first.`,
        server.configPath,
        server.installationId ?? server.id
      ))
    }
    if (server.transport === 'sse' && cliType === 'codex') {
      diagnostics.push(unsupportedDiagnostic(
        'Codex materialization does not claim legacy SSE support; use Streamable HTTP or the native Mousse connection.',
        server.configPath,
        server.installationId ?? server.id
      ))
    }
  }
  return diagnostics
}

function uniqueMaterializedNames(
  servers: McpServerConfig[],
  existing: string[] | string,
  format: 'json' | 'toml'
): string[] {
  const occupied = new Set<string>(Array.isArray(existing) ? existing : parseTomlSectionNames(existing))
  const used = new Set<string>()
  return servers.map((server) => {
    let name = server.name
    if (occupied.has(name) || used.has(name)) name = `${server.name}__mousse_${shortHash(server.installationId ?? server.id)}`
    let suffix = 2
    while (occupied.has(name) || used.has(name)) name = `${server.name}__mousse_${shortHash(server.installationId ?? server.id)}_${suffix++}`
    used.add(name)
    void format
    return name
  })
}

function parseTomlSectionNames(raw: string): string[] {
  const names: string[] = []
  for (const match of raw.matchAll(/^\s*\[mcp_servers\.(?:"((?:\\.|[^"])*)"|([A-Za-z0-9_-]+))\]\s*$/gm)) {
    names.push(match[1] ?? match[2] ?? '')
  }
  return names
}

function renderMcpEntry(cliType: AgentTypeId, server: McpServerConfig): Record<string, unknown> {
  if (cliType === 'opencode') {
    return server.transport === 'stdio'
      ? compactObject({ type: 'local', command: [server.command, ...(server.args ?? [])].filter(Boolean), environment: server.env, enabled: true })
      : compactObject({ type: 'remote', url: server.url, headers: server.headers, enabled: true })
  }
  return server.transport === 'stdio'
    ? compactObject({ command: server.command, args: server.args, env: server.env, cwd: server.cwd })
    : compactObject({ url: server.url, headers: server.headers, transport: server.transport })
}

async function restoreOwnedConfig(action: Extract<CleanupAction, { kind: 'config' }>): Promise<boolean> {
  if (!existsSync(action.path)) return false
  try {
    const current = await readFile(action.path, 'utf-8')
    // Never remove or rewrite a config that changed after materialization.
    if (current !== action.written) return false
    if (action.before === null) await rm(action.path, { force: true })
    else await atomicWriteFile(action.path, action.before)
    return true
  } catch {
    // Cleanup never destroys an unreadable or concurrently changed user file.
    return false
  }
}

function toEnvName(value: string): string {
  return value.replace(/[^A-Za-z0-9_]/g, '_').replace(/_+/g, '_').toUpperCase()
}

export function getAgentConfigHome(agentId: string, generatedConfigRoot?: string): string {
  if (generatedConfigRoot) return join(generatedConfigRoot, agentId)
  return getGeneratedAgentConfigRoot(agentId)
}

