import { existsSync } from 'fs'
import { cp, mkdir, rm, writeFile } from 'fs/promises'
import { dirname, join, relative } from 'path'
import type {
  AgentConfigPreparationResult,
  McpServerConfig,
  SkillDescriptor
} from '../../../shared/integrations'
import type { AgentTypeId } from '../../../shared/settings'
import type { SettingsStore } from '../../settings/SettingsStore'
import { getGeneratedAgentConfigRoot } from '../../data/paths'
import { McpRegistry } from '../mcp/McpRegistry'
import { SkillsRegistry } from '../skills/SkillsRegistry'

const MOUSSE_MARKER = 'Generated by Mousse for an ephemeral agent worktree.'

export class AgentConfigManager {
  private cleanupByAgent = new Map<string, { worktreePath: string; paths: string[] }>()

  constructor(
    private mcpRegistry: McpRegistry,
    private skillsRegistry: SkillsRegistry,
    private settingsStore: SettingsStore
  ) {}

  async prepare(
    agentId: string,
    cliType: AgentTypeId,
    worktreePath: string,
    projectPath: string
  ): Promise<AgentConfigPreparationResult> {
    const settings = this.settingsStore.get().integrations
    const result: AgentConfigPreparationResult = {
      agentId,
      cliType,
      generatedFiles: [],
      cleanupPaths: [],
      env: {},
      warnings: [],
      logs: []
    }

    if (settings.mcp.enabled && settings.mcp.enableForAgents[cliType]) {
      const servers = await this.getSelectedMcpServers(projectPath)
      await this.materializeMcp(cliType, worktreePath, servers, result)
    }

    if (settings.skills.enabled && settings.skills.enableForAgents[cliType]) {
      const skills = await this.getSelectedSkills(projectPath)
      await this.materializeSkills(cliType, worktreePath, skills, result)
    }

    if (result.cleanupPaths.length > 0) {
      this.cleanupByAgent.set(agentId, {
        worktreePath,
        paths: [...result.cleanupPaths]
      })
    }

    return result
  }

  async cleanup(agentId: string): Promise<string[]> {
    const cleanup = this.cleanupByAgent.get(agentId)
    const logs: string[] = []
    if (!cleanup) return logs

    for (const path of cleanup.paths) {
      // Cleanup is recursive, so never trust a remembered path without checking it again.
      // A malformed skill name or stale record must not escape the isolated worktree.
      if (!isInside(path, cleanup.worktreePath)) {
        logs.push(`[integrations] Refused cleanup outside agent worktree: ${path}`)
        continue
      }
      await rm(path, { recursive: true, force: true }).catch(() => {})
      logs.push(`[integrations] Removed generated config ${path}`)
    }
    this.cleanupByAgent.delete(agentId)
    return logs
  }

  private async getSelectedMcpServers(projectPath: string): Promise<McpServerConfig[]> {
    const enabled = new Set(this.settingsStore.get().integrations.mcp.enabledServers)
    if (enabled.size === 0) return []
    const snapshot = await this.mcpRegistry.discover({ projectPath, redactSecrets: false })
    return snapshot.servers.filter((server) => enabled.has(server.id) || enabled.has(server.name))
  }

  private async getSelectedSkills(projectPath: string): Promise<SkillDescriptor[]> {
    const enabled = new Set(this.settingsStore.get().integrations.skills.enabledSkills)
    if (enabled.size === 0) return []
    const snapshot = await this.skillsRegistry.discover({ projectPath })
    return snapshot.skills.filter(
      (skill) => skill.isActive !== false && (enabled.has(skill.id) || enabled.has(skill.name))
    )
  }

  private async materializeMcp(
    cliType: AgentTypeId,
    worktreePath: string,
    servers: McpServerConfig[],
    result: AgentConfigPreparationResult
  ): Promise<void> {
    if (servers.length === 0) return
    const target = getMcpTarget(cliType, worktreePath)
    if (existsSync(target)) {
      result.logs.push(`[integrations] Preserved existing ${relative(worktreePath, target)} for ${cliType}`)
      return
    }

    const rendered = renderMcpConfig(cliType, servers)
    await mkdir(dirname(target), { recursive: true })
    await writeFile(target, rendered, 'utf-8')
    result.generatedFiles.push(target)
    result.cleanupPaths.push(target)
    result.logs.push(`[integrations] Generated ${relative(worktreePath, target)} for ${cliType}`)
  }

  private async materializeSkills(
    cliType: AgentTypeId,
    worktreePath: string,
    skills: SkillDescriptor[],
    result: AgentConfigPreparationResult
  ): Promise<void> {
    if (skills.length === 0) return
    const roots = getSkillTargets(cliType, worktreePath)

    for (const skill of skills) {
      for (const root of roots) {
        const target = join(root, skill.name)
        if (!isInside(target, worktreePath)) {
          result.warnings.push(
            `[integrations] Refused skill path outside agent worktree: ${skill.name}`
          )
          continue
        }
        if (isInside(skill.rootPath, worktreePath) || existsSync(target)) continue
        await mkdir(dirname(target), { recursive: true })
        await cp(skill.rootPath, target, { recursive: true })
        result.generatedFiles.push(target)
        result.cleanupPaths.push(target)
      }
    }

    if (skills.length > 0) {
      result.logs.push(`[integrations] Materialized ${skills.length} skill folder${skills.length === 1 ? '' : 's'} for ${cliType}`)
    }
  }
}

export function getMcpTarget(cliType: AgentTypeId, worktreePath: string): string {
  switch (cliType) {
    case 'claude-code':
      return join(worktreePath, '.mcp.json')
    case 'codex':
      return join(worktreePath, '.codex', 'config.toml')
    case 'opencode':
      return join(worktreePath, 'opencode.json')
    case 'cursor-agents-cli':
      return join(worktreePath, '.cursor', 'mcp.json')
    case 'mousse':
      return join(worktreePath, '.mousse', 'mcp.json')
  }
}

export function getSkillTargets(cliType: AgentTypeId, worktreePath: string): string[] {
  switch (cliType) {
    case 'claude-code':
      return [join(worktreePath, '.claude', 'skills'), join(worktreePath, '.agents', 'skills')]
    case 'codex':
      return [join(worktreePath, '.codex', 'skills'), join(worktreePath, '.agents', 'skills')]
    case 'opencode':
      return [join(worktreePath, '.opencode', 'skills')]
    case 'cursor-agents-cli':
      return [join(worktreePath, '.cursor', 'skills'), join(worktreePath, '.agents', 'skills')]
    case 'mousse':
      return [join(worktreePath, '.mousse', 'skills')]
  }
}

export function renderMcpConfig(cliType: AgentTypeId, servers: McpServerConfig[]): string {
  const safeServers = servers.map(sanitizeServerForGeneratedConfig)
  switch (cliType) {
    case 'claude-code':
    case 'cursor-agents-cli':
      return `${JSON.stringify({ _comment: MOUSSE_MARKER, mcpServers: renderCursorLikeServers(safeServers) }, null, 2)}\n`
    case 'codex':
      return renderCodexToml(safeServers)
    case 'opencode':
      return `${JSON.stringify({ $comment: MOUSSE_MARKER, mcp: renderOpenCodeServers(safeServers) }, null, 2)}\n`
    case 'mousse':
      return `${JSON.stringify({ _comment: MOUSSE_MARKER, mcpServers: renderCursorLikeServers(safeServers) }, null, 2)}\n`
  }
}

function renderCursorLikeServers(servers: McpServerConfig[]): Record<string, unknown> {
  return Object.fromEntries(
    servers.map((server) => [
      server.name,
      server.transport === 'stdio'
        ? compactObject({
            command: server.command,
            args: server.args,
            env: server.env,
            cwd: server.cwd
          })
        : compactObject({
            url: server.url,
            headers: server.headers,
            transport: server.transport
          })
    ])
  )
}

function renderOpenCodeServers(servers: McpServerConfig[]): Record<string, unknown> {
  return Object.fromEntries(
    servers.map((server) => [
      server.name,
      server.transport === 'stdio'
        ? compactObject({
            type: 'local',
            command: [server.command, ...(server.args ?? [])].filter(Boolean),
            environment: server.env,
            enabled: true
          })
        : compactObject({
            type: 'remote',
            url: server.url,
            headers: server.headers,
            enabled: true
          })
    ])
  )
}

function renderCodexToml(servers: McpServerConfig[]): string {
  const lines = [`# ${MOUSSE_MARKER}`]
  for (const server of servers) {
    lines.push('', `[mcp_servers.${quoteTomlKey(server.name)}]`)
    if (server.command) lines.push(`command = ${tomlValue(server.command)}`)
    if (server.args?.length) lines.push(`args = ${tomlValue(server.args)}`)
    if (server.env && Object.keys(server.env).length > 0) {
      lines.push(`env = ${tomlValue(server.env)}`)
    }
    if (server.cwd) lines.push(`cwd = ${tomlValue(server.cwd)}`)
    if (server.url) lines.push(`url = ${tomlValue(server.url)}`)
    if (server.headers && Object.keys(server.headers).length > 0) {
      lines.push(`http_headers = ${tomlValue(server.headers)}`)
    }
    lines.push('enabled = true')
  }
  return `${lines.join('\n')}\n`
}

function compactObject(value: Record<string, unknown>): Record<string, unknown> {
  return Object.fromEntries(
    Object.entries(value).filter(([, entry]) => entry !== undefined && entry !== null)
  )
}

function tomlValue(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(tomlValue).join(', ')}]`
  if (value && typeof value === 'object') {
    return `{ ${Object.entries(value as Record<string, unknown>)
      .map(([key, entry]) => `${quoteTomlKey(key)} = ${tomlValue(entry)}`)
      .join(', ')} }`
  }
  if (typeof value === 'boolean') return value ? 'true' : 'false'
  return JSON.stringify(String(value))
}

function quoteTomlKey(key: string): string {
  return /^[A-Za-z0-9_-]+$/.test(key) ? key : JSON.stringify(key)
}

function isInside(child: string, parent: string): boolean {
  const rel = relative(parent, child)
  return Boolean(rel) && !rel.startsWith('..') && !rel.startsWith('/')
}

function sanitizeServerForGeneratedConfig(server: McpServerConfig): McpServerConfig {
  return {
    ...server,
    env: sanitizeSecretRecord(server.env, (key) => `\${env:${toEnvName(key)}}`),
    headers: sanitizeSecretRecord(
      server.headers,
      (key) => `\${env:MCP_${toEnvName(server.name)}_${toEnvName(key)}}`
    )
  }
}

function sanitizeSecretRecord(
  record: Record<string, string> | undefined,
  placeholder: (key: string) => string
): Record<string, string> | undefined {
  if (!record) return undefined
  return Object.fromEntries(
    Object.entries(record).map(([key, value]) => [
      key,
      containsEnvReference(value) ? value : placeholder(key)
    ])
  )
}

function containsEnvReference(value: string): boolean {
  return (
    /\$\{env:[A-Za-z_][A-Za-z0-9_]*}/.test(value) ||
    /\$\{[A-Za-z_][A-Za-z0-9_]*}/.test(value) ||
    /(^|[^A-Za-z0-9_])\$[A-Za-z_][A-Za-z0-9_]*/.test(value) ||
    /%[A-Za-z_][A-Za-z0-9_]*%/.test(value)
  )
}

function toEnvName(value: string): string {
  return value.replace(/[^A-Za-z0-9_]/g, '_').replace(/_+/g, '_').toUpperCase()
}

export function getAgentConfigHome(agentId: string): string {
  return getGeneratedAgentConfigRoot(agentId)
}

