import { existsSync, lstatSync } from 'node:fs'
import { spawn, type ChildProcess } from 'node:child_process'
import type { CliAgentRuntimePort, AgentRuntimeInput, AgentRuntimeResult } from '../../shared/agents/execution'
import type { AgentRuntimeKind } from '../../shared/agents/types'
import { killProcessTree } from '../execution/processTree'

const DEFAULT_MAX_OUTPUT_BYTES = 4 * 1024 * 1024

export interface CliProcessInvocation {
  command: string
  args: string[]
  cwd?: string
  env?: Record<string, string>
  promptMode?: 'argument' | 'stdin'
  /** Called exactly once after a run, including spawn failure, abort, or crash. */
  cleanup?: () => void | Promise<void>
}

export interface CliProcessRuntimeOptions {
  /** Resolve an installed CLI and its supported system-instruction/config flags. */
  resolveInvocation(input: AgentRuntimeInput): CliProcessInvocation | Promise<CliProcessInvocation>
  spawn?: typeof spawn
  /** Combined stdout/stderr capture bound. */
  maxOutputBytes?: number
}

export interface QualifiedCliProcessRuntimeOptions {
  prepareInvocation(input: AgentRuntimeInput): (SupportedCliInvocationOptions & { cleanup?: () => void | Promise<void> }) | Promise<SupportedCliInvocationOptions & { cleanup?: () => void | Promise<void> }>
  spawn?: typeof spawn
  maxOutputBytes?: number
}

export interface SupportedCliInvocationOptions {
  commands?: Partial<Record<Exclude<AgentRuntimeKind, 'mousse'>, string | { command: string; args?: string[] }>>
  /** Existing per-worktree MCP config generated by AgentConfigManager. */
  mcpConfigPath?: string
  /** Exact Claude CLI tool name for each granted `serverId/toolName` identity. */
  claudeMcpToolNames?: Record<string, string>
  /** Cursor CLI has no system-prompt flag; pass a materialized project rules file. */
  cursorRulesPath?: string
  /** Allow the host to materialize the OpenCode agent config in a disposable file. */
  openCodeConfigPath?: string
  /** Fail-closed materialization errors produced before invocation construction. */
  materializationErrors?: readonly { message: string; targetId?: string }[]
}

export interface CliCapabilityIssue {
  code: 'missing_materialization' | 'unsupported_permission' | 'unknown_tool_mapping' | 'invalid_materialization'
  message: string
  grantIds?: string[]
}

export interface CliCapabilityReport {
  runtimeKind: Exclude<AgentRuntimeKind, 'mousse'>
  supported: boolean
  consumedGrantIds: string[]
  issues: CliCapabilityIssue[]
}

export class CliCapabilityError extends Error {
  readonly code = 'CLI_CAPABILITY_UNSUPPORTED'
  constructor(readonly report: CliCapabilityReport) {
    super(report.issues.map((issue) => issue.message).join(' '))
    this.name = 'CliCapabilityError'
  }
}

const DEFAULT_CLI_COMMANDS: Record<Exclude<AgentRuntimeKind, 'mousse'>, string> = {
  'claude-code': 'claude',
  codex: 'codex',
  opencode: 'opencode',
  'cursor-agents-cli': 'cursor-agent'
}

/**
 * Build invocations using each CLI's documented instruction mechanism. Cursor
 * requires a materialized rules file because its print CLI has no system prompt
 * flag; silently placing instructions in an unread environment variable is not
 * accepted here.
 */
export function buildSupportedCliInvocation(
  input: AgentRuntimeInput,
  options: SupportedCliInvocationOptions = {}
): CliProcessInvocation {
  if (input.runtimeKind === 'mousse') throw new Error('Mousse uses the native runtime adapter.')
  const configuredCommand = options.commands?.[input.runtimeKind]
  const command = typeof configuredCommand === 'object' ? configuredCommand.command : configuredCommand ?? DEFAULT_CLI_COMMANDS[input.runtimeKind]
  const model = input.model.primary.ref.modelId
  const args: string[] = typeof configuredCommand === 'object' ? [...(configuredCommand.args ?? [])] : []
  let promptMode: CliProcessInvocation['promptMode'] = 'argument'
  switch (input.runtimeKind) {
    case 'claude-code': {
      const mcpAllowed = input.grants.mcpTools.map((grant) => {
        const name = options.claudeMcpToolNames?.[grant.id]
        if (!name) throw new Error(`Claude CLI tool mapping is required for granted MCP tool ${grant.id}.`)
        return name
      })
      if (mcpAllowed.length > 0 && !options.mcpConfigPath) {
        throw new Error('Claude CLI requires the materialized MCP config for granted MCP tools.')
      }
      const allowed = [...input.grants.builtinTools.map((grant) => mapClaudeTool(grant.id)), ...mcpAllowed]
      args.push(
        '--bare', '--disable-slash-commands', '--no-session-persistence',
        '-p', '--output-format', 'text', '--system-prompt', input.systemPrompt,
        '--model', model, '--max-turns', String(input.budget.maxTurns),
        '--tools', ...(allowed.length ? allowed : [''])
      )
      if (options.mcpConfigPath) args.push('--strict-mcp-config', '--mcp-config', options.mcpConfigPath)
      if (allowed.length) args.push('--allowedTools', ...allowed)
      promptMode = 'stdin'
      break
    }
    case 'codex':
      args.push('exec', '--ephemeral', '--ignore-user-config', '--ignore-rules', '--strict-config', '-s', 'workspace-write', '-m', model, '-c', `developer_instructions=${JSON.stringify(input.systemPrompt)}`)
      promptMode = 'stdin'
      break
    case 'opencode': {
      args.push('run', '--agent', 'mousse', '-m', `${input.model.primary.ref.providerId}/${model}`)
      const config = {
        $schema: 'https://opencode.ai/config.json',
        agent: { mousse: { mode: 'primary', model: `${input.model.primary.ref.providerId}/${model}`, prompt: input.systemPrompt } }
      }
      const env: Record<string, string> = options.openCodeConfigPath
        ? { OPENCODE_CONFIG: options.openCodeConfigPath }
        : { OPENCODE_CONFIG_CONTENT: JSON.stringify(config) }
      return { command, args, cwd: input.projectPath, env, promptMode: 'argument' }
    }
    case 'cursor-agents-cli':
      if (!options.cursorRulesPath) throw new Error('Cursor CLI requires a materialized rules file for agent instructions.')
      args.push('-p', '--output-format', 'text', '--model', model)
      break
  }
  return { command, args, cwd: input.projectPath, promptMode }
}

/**
 * Report whether the installed-runtime contract can enforce every resolved
 * integration grant. A normal builder is retained for inspection and legacy
 * callers; production execution must use this qualified entry point.
 */
export function inspectCliCapabilities(
  input: AgentRuntimeInput,
  options: SupportedCliInvocationOptions = {}
): CliCapabilityReport {
  if (input.runtimeKind === 'mousse') throw new Error('Mousse uses the native runtime adapter.')
  const issues: CliCapabilityIssue[] = []
  const consumedGrantIds: string[] = []
  const builtinIds = input.grants.builtinTools.map((grant) => grant.id)
  const mcpIds = input.grants.mcpTools.map((grant) => grant.id)
  const skillIds = input.grants.skills.map((grant) => grant.id)

  for (const issue of options.materializationErrors ?? []) {
    issues.push({ code: 'invalid_materialization', message: issue.message, ...(issue.targetId ? { grantIds: [issue.targetId] } : {}) })
  }

  if (input.runtimeKind === 'claude-code') {
    if (mcpIds.length > 0 && !options.mcpConfigPath) {
      issues.push({ code: 'missing_materialization', message: 'Claude MCP grants require a strict, profile-owned MCP config.', grantIds: mcpIds })
    }
    const unknownBuiltin = builtinIds.filter((id) => !mapClaudeTool(id))
    if (unknownBuiltin.length > 0) {
      issues.push({ code: 'unsupported_permission', message: `Claude cannot enforce these Mousse built-in grants through its documented tool surface: ${unknownBuiltin.join(', ')}`, grantIds: unknownBuiltin })
    }
    const missingMapping = input.grants.mcpTools.filter((grant) => !options.claudeMcpToolNames?.[grant.id]).map((grant) => grant.id)
    if (missingMapping.length > 0) {
      issues.push({ code: 'unknown_tool_mapping', message: `Claude requires an exact runtime MCP tool-name mapping for: ${missingMapping.join(', ')}`, grantIds: missingMapping })
    }
    if (options.mcpConfigPath && missingMapping.length === 0) consumedGrantIds.push(...mcpIds)
    consumedGrantIds.push(...builtinIds.filter((id) => Boolean(mapClaudeTool(id))))
  } else {
    issues.push({
      code: 'unsupported_permission',
      message: `${input.runtimeKind} has no qualified exact tool allowlist; refusing to run its unrestricted built-in tool surface.`,
      ...(builtinIds.length ? { grantIds: builtinIds } : {})
    })
  }

  if (skillIds.length > 0) {
    issues.push({ code: 'unsupported_permission', message: `${input.runtimeKind} has no qualified exact Skill allowlist; refusing to expose materialized skills.`, grantIds: skillIds })
  }

  if (mcpIds.length > 0 && input.runtimeKind !== 'claude-code') {
    issues.push({ code: 'unsupported_permission', message: `${input.runtimeKind} has no qualified exact MCP tool permission surface; refusing to expose granted MCP tools.`, grantIds: mcpIds })
  }
  if (input.runtimeKind === 'cursor-agents-cli' && !options.cursorRulesPath) {
    issues.push({ code: 'missing_materialization', message: 'Cursor Agent requires a profile-owned rules file for the resolved system instructions.' })
  }
  if (input.runtimeKind === 'opencode' && !options.openCodeConfigPath) {
    issues.push({ code: 'missing_materialization', message: 'OpenCode requires a profile-owned config file for the resolved agent instructions.' })
  }
  for (const [label, path] of [['MCP config', options.mcpConfigPath], ['Cursor rules', options.cursorRulesPath], ['OpenCode config', options.openCodeConfigPath] as const]) {
    if (!path) continue
    try {
      if (!existsSync(path) || !lstatSync(path).isFile()) issues.push({ code: 'invalid_materialization', message: `${label} materialization is missing or is not a regular file: ${path}` })
    } catch {
      issues.push({ code: 'invalid_materialization', message: `${label} materialization cannot be inspected: ${path}` })
    }
  }
  return { runtimeKind: input.runtimeKind, supported: issues.length === 0, consumedGrantIds: [...new Set(consumedGrantIds)], issues }
}

/** Build only after the host has supplied and qualified every materialized grant. */
export function buildQualifiedCliInvocation(
  input: AgentRuntimeInput,
  options: SupportedCliInvocationOptions = {}
): CliProcessInvocation {
  const report = inspectCliCapabilities(input, options)
  if (!report.supported) throw new CliCapabilityError(report)
  return buildSupportedCliInvocation(input, options)
}

function mapClaudeTool(id: string): string {
  switch (id) {
    case 'read': return 'Read'
    case 'write': return 'Edit'
    case 'bash': return 'Bash'
    case 'grep': return 'Grep'
    case 'ls': return 'Glob'
    default: return ''
  }
}

function abortError(): DOMException {
  return new DOMException('Agent process was aborted.', 'AbortError')
}

/**
 * Process adapter for external runtimes. It never concatenates system instructions
 * into the user prompt. The invocation resolver may map the separate systemPrompt
 * to a runtime-supported config file/flag.
 */
export function createCliProcessRuntime(options: CliProcessRuntimeOptions): CliAgentRuntimePort {
  const spawnProcess = options.spawn ?? spawn
  return {
    async run(input): Promise<AgentRuntimeResult> {
      if (input.signal.aborted) throw abortError()
      const invocation = await options.resolveInvocation(input)
      if (input.signal.aborted) { await invocation.cleanup?.(); throw abortError() }
      if (!invocation.command.trim()) { await invocation.cleanup?.(); throw new Error('CLI invocation command is empty.') }
      const maxOutputBytes = options.maxOutputBytes ?? DEFAULT_MAX_OUTPUT_BYTES
      if (!Number.isSafeInteger(maxOutputBytes) || maxOutputBytes <= 0) { await invocation.cleanup?.(); throw new Error('CLI output byte limit must be a positive integer.') }
      const env: NodeJS.ProcessEnv = { ...process.env, ...invocation.env }
      const args = invocation.promptMode === 'argument'
        ? [...invocation.args, input.userMessage]
        : invocation.args
      let child: ChildProcess
      try {
        child = spawnProcess(invocation.command, args, {
          cwd: invocation.cwd ?? input.projectPath,
          env,
          stdio: ['pipe', 'pipe', 'pipe'],
          windowsHide: true,
          detached: process.platform !== 'win32'
        })
      } catch (error) {
        await invocation.cleanup?.()
        throw error
      }
      let stdout = ''
      let stderr = ''
      let capturedBytes = 0
      let outputLimitExceeded = false
      const terminate = (): void => {
        if (child.pid) killProcessTree(child.pid)
        child.kill()
      }
      const capture = (stream: 'stdout' | 'stderr', chunk: string): void => {
        if (outputLimitExceeded) return
        capturedBytes += Buffer.byteLength(chunk)
        if (capturedBytes > maxOutputBytes) {
          outputLimitExceeded = true
          terminate()
          return
        }
        if (stream === 'stdout') stdout += chunk
        else stderr += chunk
      }
      child.stdout?.setEncoding('utf8')
      child.stderr?.setEncoding('utf8')
      child.stdout?.on('data', (chunk: string) => capture('stdout', chunk))
      child.stderr?.on('data', (chunk: string) => capture('stderr', chunk))

      let aborted = false
      const onAbort = (): void => {
        aborted = true
        terminate()
      }
      input.signal.addEventListener('abort', onAbort, { once: true })
      try {
        if (invocation.promptMode === 'argument') child.stdin?.end()
        else child.stdin?.end(input.userMessage)
        const [code, signal] = await waitForExit(child)
        if (aborted || input.signal.aborted) throw abortError()
        if (outputLimitExceeded) throw new Error(`CLI agent exceeded its ${maxOutputBytes}-byte output limit.`)
        if (code !== 0) {
          const detail = stderr.trim() || stdout.trim() || `signal ${signal ?? 'unknown'}`
          throw new Error(`CLI agent exited with code ${String(code)}: ${detail}`)
        }
        return { text: stdout }
      } finally {
        input.signal.removeEventListener('abort', onAbort)
        if (!child.killed && input.signal.aborted) terminate()
        await invocation.cleanup?.()
      }
    }
  }
}

/** Runtime factory that cannot be configured without a capability-qualified materialization. */
export function createQualifiedCliProcessRuntime(options: QualifiedCliProcessRuntimeOptions): CliAgentRuntimePort {
  return createCliProcessRuntime({
    spawn: options.spawn,
    maxOutputBytes: options.maxOutputBytes,
    resolveInvocation: async (input) => {
      const prepared = await options.prepareInvocation(input)
      try {
        const invocation = buildQualifiedCliInvocation(input, prepared)
        return { ...invocation, cleanup: prepared.cleanup }
      } catch (error) {
        await prepared.cleanup?.()
        throw error
      }
    }
  })
}

function waitForExit(child: ChildProcess): Promise<[number | null, NodeJS.Signals | null]> {
  return new Promise((resolve, reject) => {
    child.once('error', reject)
    child.once('close', (code, signal) => resolve([code, signal]))
  })
}
