import { spawn, type ChildProcess } from 'node:child_process'
import type { CliAgentRuntimePort, AgentRuntimeInput, AgentRuntimeResult } from '../../shared/agents/execution'
import type { AgentRuntimeKind } from '../../shared/agents/types'

export interface CliProcessInvocation {
  command: string
  args: string[]
  cwd?: string
  env?: Record<string, string>
  promptMode?: 'argument' | 'stdin'
}

export interface CliProcessRuntimeOptions {
  /** Resolve an installed CLI and its supported system-instruction/config flags. */
  resolveInvocation(input: AgentRuntimeInput): CliProcessInvocation | Promise<CliProcessInvocation>
  spawn?: typeof spawn
}

export interface SupportedCliInvocationOptions {
  commands?: Partial<Record<Exclude<AgentRuntimeKind, 'mousse'>, string>>
  /** Existing per-worktree MCP config generated by AgentConfigManager. */
  mcpConfigPath?: string
  /** Cursor CLI has no system-prompt flag; pass a materialized project rules file. */
  cursorRulesPath?: string
  /** Allow the host to materialize the OpenCode agent config in a disposable file. */
  openCodeConfigPath?: string
}

const DEFAULT_CLI_COMMANDS: Record<Exclude<AgentRuntimeKind, 'mousse'>, string> = {
  'claude-code': 'claude',
  codex: 'codex',
  opencode: 'opencode',
  'cursor-agents-cli': 'cursor-agent'
}

/**
 * Build invocations using each CLI's documented instruction mechanism. Cursor
 * requires a materialized rules file because its print CLI has no system prompt
 * flag; silently placing instructions in an unread environment variable is not
 * accepted here.
 */
export function buildSupportedCliInvocation(
  input: AgentRuntimeInput,
  options: SupportedCliInvocationOptions = {}
): CliProcessInvocation {
  if (input.runtimeKind === 'mousse') throw new Error('Mousse uses the native runtime adapter.')
  const command = options.commands?.[input.runtimeKind] ?? DEFAULT_CLI_COMMANDS[input.runtimeKind]
  const model = input.model.primary.ref.modelId
  const args: string[] = []
  switch (input.runtimeKind) {
    case 'claude-code': {
      args.push('-p', '--output-format', 'text', '--system-prompt', input.systemPrompt, '--model', model, '--max-turns', String(input.budget.maxTurns))
      if (options.mcpConfigPath) args.push('--mcp-config', options.mcpConfigPath)
      const allowed = input.grants.builtinTools.map((grant) => mapClaudeTool(grant.id))
      if (allowed.length) args.push('--allowedTools', ...allowed)
      break
    }
    case 'codex':
      args.push('exec', '-m', model, '-c', `developer_instructions=${JSON.stringify(input.systemPrompt)}`)
      break
    case 'opencode': {
      args.push('run', '--agent', 'mousse', '-m', `${input.model.primary.ref.providerId}/${model}`)
      const config = {
        $schema: 'https://opencode.ai/config.json',
        agent: { mousse: { mode: 'primary', model: `${input.model.primary.ref.providerId}/${model}`, prompt: input.systemPrompt } }
      }
      const env: Record<string, string> = { OPENCODE_CONFIG_CONTENT: JSON.stringify(config) }
      if (options.openCodeConfigPath) env.OPENCODE_CONFIG = options.openCodeConfigPath
      return { command, args, cwd: input.projectPath, env, promptMode: 'argument' }
    }
    case 'cursor-agents-cli':
      if (!options.cursorRulesPath) throw new Error('Cursor CLI requires a materialized rules file for agent instructions.')
      args.push('-p', '--output-format', 'text', '--model', model, '--force')
      break
  }
  return { command, args, cwd: input.projectPath, promptMode: 'argument' }
}

function mapClaudeTool(id: string): string {
  switch (id) {
    case 'read': return 'Read'
    case 'write': return 'Edit'
    case 'bash': return 'Bash'
    case 'grep': return 'Grep'
    case 'ls': return 'Glob'
    default: return id
  }
}

function abortError(): DOMException {
  return new DOMException('Agent process was aborted.', 'AbortError')
}

/**
 * Process adapter for external runtimes. It never concatenates system instructions
 * into the user prompt. The invocation resolver may map the separate systemPrompt
 * to a runtime-supported config file/flag.
 */
export function createCliProcessRuntime(options: CliProcessRuntimeOptions): CliAgentRuntimePort {
  const spawnProcess = options.spawn ?? spawn
  return {
    async run(input): Promise<AgentRuntimeResult> {
      if (input.signal.aborted) throw abortError()
      const invocation = await options.resolveInvocation(input)
      if (!invocation.command.trim()) throw new Error('CLI invocation command is empty.')
      const env: NodeJS.ProcessEnv = { ...process.env, ...invocation.env }
      const args = invocation.promptMode === 'argument'
        ? [...invocation.args, input.userMessage]
        : invocation.args
      const child = spawnProcess(invocation.command, args, {
        cwd: invocation.cwd ?? input.projectPath,
        env,
        stdio: ['pipe', 'pipe', 'pipe'],
        windowsHide: true
      })
      let stdout = ''
      let stderr = ''
      child.stdout?.setEncoding('utf8')
      child.stderr?.setEncoding('utf8')
      child.stdout?.on('data', (chunk: string) => { stdout += chunk })
      child.stderr?.on('data', (chunk: string) => { stderr += chunk })

      let aborted = false
      const onAbort = (): void => {
        aborted = true
        child.kill()
      }
      input.signal.addEventListener('abort', onAbort, { once: true })
      try {
        if (invocation.promptMode === 'argument') child.stdin?.end()
        else child.stdin?.end(input.userMessage)
        const [code, signal] = await waitForExit(child)
        if (aborted || input.signal.aborted) throw abortError()
        if (code !== 0) {
          const detail = stderr.trim() || stdout.trim() || `signal ${signal ?? 'unknown'}`
          throw new Error(`CLI agent exited with code ${String(code)}: ${detail}`)
        }
        return { text: stdout }
      } finally {
        input.signal.removeEventListener('abort', onAbort)
        if (!child.killed && input.signal.aborted) child.kill()
      }
    }
  }
}

function waitForExit(child: ChildProcess): Promise<[number | null, NodeJS.Signals | null]> {
  return new Promise((resolve, reject) => {
    child.once('error', reject)
    child.once('close', (code, signal) => resolve([code, signal]))
  })
}
