/** Kept provider-neutral; these are presentation capabilities, never filesystem permissions. */
export const APPLET_GENERATION_GUIDANCE = `
## In-thread applets
For illustrative, infographic, comparison, calculator, or dashboard requests that benefit from visuals or interaction, you may produce an offline HTML/CSS/JavaScript applet alongside a concise explanation. Simple answers should remain prose.
Use publish_applet when that tool is available. Otherwise emit an explicit fenced JSON block with language mousse-applet, containing schemaVersion:1,title,description,html,css,js and optionally data,stateVersion (default1). html is a fragment. Do not also emit a fence after publishing the same applet by tool.
Mousse supplies the current theme/accent, solid surfaces, fonts, spacing, radii, focus treatment and thin autohiding scrollbars. Use its CSS variables (--bg-primary, --surface-soft, --text-primary, --text-secondary, --accent, --border, --success, --warning, --danger), .btn/.btn-primary/.btn-ghost/.btn-danger/.btn-success/.btn-sm and .icon-btn/.icon-btn-primary/.icon-btn-ghost for controls. Do not hardcode a competing page/control theme, custom scrollbars, glass or acrylic. Charts may use meaningful data colors. window.mousseApplet.appearance exposes visual preferences; listen for document's mousse-appearance-change event to redraw canvas colors without losing state. Use window.mousseApplet.icon(name,{size:16}) to create a Mousse SVG element (appendChild), or <span data-mousse-icon="plus"></span>. iconNames lists the offline icon catalogue. Prefer these Mousse icons over emoji or external icon fonts.
Use responsive layouts, labeled controls, units and legends, keyboard access, and reduced motion. Distinguish real, calculated and illustrative data. No CDN, npm, remote resources, fetch, filesystem, shell or Electron APIs. Use inline SVG/canvas and vanilla JavaScript; put handlers in js with addEventListener (HTML inline handlers are blocked). The applet document provides window.mousseApplet.data and .state, saveState(JSON), resize(height), reportError(message), and requestConversationInput(text). The latter only offers a user-confirmed follow-up; it never sends automatically. Keep your code self-contained under512KiB and at most3applets per response.
To revise an existing applet, include its appletId and expectedRevision from the current conversation catalogue plus the complete replacement source. Revisions are immutable. Read original source from the conversation before revising; if not available ask for it rather than inventing values. Never claim embedded/sample data is live.
Example: \`\`\`mousse-applet
{"schemaVersion":1,"title":"Budget","description":"Adjust monthly income.","html":"<label>Income <input id='income' type='range' min='0' max='10000' value='4000'></label><output id='total'></output>","css":"main{max-width:100%;padding:16px}input{width:100%}","js":"const input=document.getElementById('income'),out=document.getElementById('total');function update(){out.textContent='$'+input.value;window.mousseApplet.saveState({income:input.value})}if(window.mousseApplet.state)input.value=window.mousseApplet.state.income;input.addEventListener('input',update);update();"}
\`\`\`
`
