export interface VsCodeThemeColors {
  [key: string]: string
}

export interface VsCodeTokenColor {
  scope: string | string[]
  settings: {
    foreground?: string
    fontStyle?: string
    background?: string
  }
}

export interface VsCodeTheme {
  colors: VsCodeThemeColors
  tokenColors: VsCodeTokenColor[]
}

export const BLACKSPHERE_COLORS: VsCodeThemeColors = {
  "activityBar.activeBackground": "#0e0e0e",
  "activityBar.background": "#0e0e0e",
  "activityBar.border": "#272727",
  "activityBar.foreground": "#d6d6d6",
  "activityBar.inactiveForeground": "#7a797a",
  "activityBarBadge.background": "#efb080",
  "activityBarBadge.foreground": "#0e0e0e",
  "badge.background": "#efb080",
  "badge.foreground": "#0e0e0e",
  "breadcrumb.activeSelectionForeground": "#d6d6d6",
  "breadcrumb.background": "#131313",
  "breadcrumb.focusForeground": "#d6d6d6",
  "breadcrumb.foreground": "#a6a6a6",
  "button.background": "#d6d6d6",
  "button.foreground": "#000000",
  "button.hoverBackground": "#cccccc",
  "button.secondaryBackground": "#161616",
  "button.secondaryForeground": "#d6d6d6",
  "button.secondaryHoverBackground": "#303030",
  "checkbox.background": "#161616",
  "checkbox.border": "#272727",
  "checkbox.foreground": "#d6d6d6",
  "commandCenter.activeBackground": "#161616",
  "commandCenter.activeBorder": "#333333",
  "commandCenter.background": "#131313",
  "commandCenter.border": "#272727",
  "commandCenter.foreground": "#c1c1c1",
  "debugExceptionWidget.background": "#161616",
  "debugExceptionWidget.border": "#272727",
  "debugToolBar.background": "#343334",
  "debugToolBar.border": "#272727",
  "diffEditor.border": "#272727",
  "diffEditor.insertedTextBackground": "#83d6c530",
  "diffEditor.insertedTextBorder": "#d6d6d600",
  "diffEditor.removedTextBackground": "#f14c4c30",
  "diffEditor.removedTextBorder": "#d6d6d600",
  "dropdown.background": "#161616",
  "dropdown.border": "#272727",
  "dropdown.foreground": "#b3b3b3",
  "editor.background": "#131313",
  "editor.findMatchBackground": "#163764",
  "editor.findMatchBorder": "#00000000",
  "editor.findMatchHighlightBackground": "#7c511a",
  "editor.findMatchHighlightBorder": "#d7d7dd02",
  "editor.findRangeHighlightBackground": "#161616",
  "editor.findRangeHighlightBorder": "#d6d6d600",
  "editor.foldBackground": "#161616",
  "editor.foreground": "#d6d6d6",
  "editor.hoverHighlightBackground": "#5b51ec70",
  "editor.inactiveSelectionBackground": "#363636",
  "editor.lineHighlightBackground": "#d6d6d614",
  "editor.lineHighlightBorder": "#d6d6d600",
  "editor.rangeHighlightBackground": "#161616",
  "editor.rangeHighlightBorder": "#27272700",
  "editor.selectionBackground": "#d6d6d619",
  "editor.selectionHighlightBackground": "#16376170",
  "editor.selectionHighlightBorder": "#d6d6d600",
  "editor.wordHighlightBackground": "#ff000000",
  "editor.wordHighlightBorder": "#d6d6d600",
  "editor.wordHighlightStrongBackground": "#16376170",
  "editor.wordHighlightStrongBorder": "#d6d6d600",
  "editorBracketMatch.background": "#163761",
  "editorBracketMatch.border": "#d6d6d600",
  "editorCodeLens.foreground": "#d6d6d6",
  "editorCursor.background": "#131313",
  "editorCursor.foreground": "#d6d6d6",
  "editorError.background": "#b73a3400",
  "editorError.border": "#d6d6d600",
  "editorError.foreground": "#f14c4c",
  "editorGroup.border": "#272727",
  "editorGroup.dropBackground": "#d6d6d614",
  "editorGroup.emptyBackground": "#131313",
  "editorGroupHeader.border": "#d6d6d600",
  "editorGroupHeader.noTabsBackground": "#131313",
  "editorGroupHeader.tabsBackground": "#0e0e0e",
  "editorGroupHeader.tabsBorder": "#292929",
  "editorGutter.addedBackground": "#15ac91",
  "editorGutter.background": "#131313",
  "editorGutter.commentRangeForeground": "#454547",
  "editorGutter.deletedBackground": "#f14c4c",
  "editorGutter.foldingControlForeground": "#535353",
  "editorGutter.modifiedBackground": "#e5b95c",
  "editorHoverWidget.background": "#161616",
  "editorHoverWidget.border": "#272727",
  "editorHoverWidget.foreground": "#d6d6d6",
  "editorIndentGuide.activeBackground1": "#666666",
  "editorIndentGuide.background1": "#333333",
  "editorInfo.background": "#d6d6d600",
  "editorInfo.border": "#d6d6d600",
  "editorInfo.foreground": "#efb080",
  "editorInlayHint.background": "#2b2b2b",
  "editorInlayHint.foreground": "#838383",
  "editorLineNumber.activeForeground": "#cccccc",
  "editorLineNumber.foreground": "#535353",
  "editorLink.activeForeground": "#228df2",
  "editorMarkerNavigation.background": "#2d2d30",
  "editorMarkerNavigationError.background": "#f14c4c",
  "editorMarkerNavigationInfo.background": "#4c9df3",
  "editorMarkerNavigationWarning.background": "#e5b95c",
  "editorOverviewRuler.background": "#25252500",
  "editorOverviewRuler.border": "#d6d6d600",
  "editorRuler.foreground": "#333333",
  "editorSuggestWidget.background": "#161616",
  "editorSuggestWidget.border": "#272727",
  "editorSuggestWidget.foreground": "#d6d6d6",
  "editorSuggestWidget.highlightForeground": "#d6d6d6",
  "editorSuggestWidget.selectedBackground": "#163761",
  "editorWarning.background": "#a9904000",
  "editorWarning.border": "#d6d6d600",
  "editorWarning.foreground": "#ea7620",
  "editorWhitespace.foreground": "#444444",
  "editorWidget.background": "#131313",
  "editorWidget.border": "#272727",
  "editorWidget.resizeBorder": "#efb080",
  "focusBorder": "#d6d6d600",
  "foreground": "#b3b3b3",
  "gitDecoration.addedResourceForeground": "#5a964d",
  "gitDecoration.conflictingResourceForeground": "#aaa0fa",
  "gitDecoration.deletedResourceForeground": "#f14c4c",
  "gitDecoration.ignoredResourceForeground": "#666666",
  "gitDecoration.modifiedResourceForeground": "#1981ef",
  "gitDecoration.stageDeletedResourceForeground": "#f14c4c",
  "gitDecoration.stageModifiedResourceForeground": "#1981ef",
  "gitDecoration.submoduleResourceForeground": "#1981ef",
  "gitDecoration.untrackedResourceForeground": "#3ea17f",
  "icon.foreground": "#b3b3b3",
  "input.background": "#131313",
  "input.border": "#272727",
  "input.foreground": "#d6d6d6",
  "input.placeholderForeground": "#7b7b7b",
  "inputOption.activeBackground": "#efb080",
  "inputOption.activeBorder": "#d6d6d600",
  "inputOption.activeForeground": "#0e0e0e",
  "list.activeSelectionBackground": "#d6d6d619",
  "list.activeSelectionForeground": "#d6d6d6",
  "list.dropBackground": "#d6d6d600",
  "list.focusBackground": "#d6d6d60f",
  "list.focusForeground": "#d6d6d6",
  "list.highlightForeground": "#d6d6d6",
  "list.hoverBackground": "#d6d6d60f",
  "list.hoverForeground": "#d6d6d6",
  "list.inactiveSelectionBackground": "#d6d6d614",
  "list.inactiveSelectionForeground": "#b3b3b3",
  "listFilterWidget.background": "#5b51ec",
  "listFilterWidget.noMatchesOutline": "#f14c4c",
  "listFilterWidget.outline": "#00000000",
  "listFilterWidget.shadow": "#00000000",
  "menu.background": "#131313",
  "menu.border": "#000000",
  "menu.foreground": "#d6d6d6",
  "menu.selectionBackground": "#194176",
  "menu.selectionBorder": "#00000000",
  "menu.selectionForeground": "#d6d6d6",
  "menu.separatorBackground": "#3e3e3e",
  "menubar.selectionBackground": "#d6d6d620",
  "menubar.selectionBorder": "#d6d6d600",
  "menubar.selectionForeground": "#d6d6d6",
  "editorStickyScrollHover.background": "#d6d6d60f",
  "merge.commonContentBackground": "#161616",
  "merge.commonHeaderBackground": "#323232",
  "merge.currentContentBackground": "#1a493d",
  "merge.currentHeaderBackground": "#83d6c595",
  "merge.incomingContentBackground": "#28384b",
  "merge.incomingHeaderBackground": "#395f8f",
  "minimap.background": "#131313",
  "minimap.errorHighlight": "#f14c4c",
  "minimap.findMatchHighlight": "#15ac9170",
  "minimap.selectionHighlight": "#363636",
  "minimap.warningHighlight": "#ea7620",
  "minimapGutter.addedBackground": "#15ac91",
  "minimapGutter.deletedBackground": "#f14c4c",
  "minimapGutter.modifiedBackground": "#e5b95c",
  "notebook.focusedCellBorder": "#15ac91",
  "notebook.focusedEditorBorder": "#15ac9177",
  "notificationCenter.border": "#333333",
  "notificationCenterHeader.background": "#0e0e0e",
  "notificationCenterHeader.foreground": "#d6d6d6",
  "notificationToast.border": "#272727",
  "notifications.background": "#0e0e0e",
  "notifications.border": "#333333",
  "notifications.foreground": "#d6d6d6",
  "notificationsErrorIcon.foreground": "#f14c4c",
  "notificationsInfoIcon.foreground": "#228df2",
  "notificationsWarningIcon.foreground": "#ea7620",
  "panel.background": "#0e0e0e",
  "panel.border": "#272727",
  "panelSection.border": "#272727",
  "panelTitle.activeBorder": "#d6d6d6",
  "panelTitle.activeForeground": "#d6d6d6",
  "panelTitle.inactiveForeground": "#b3b3b3",
  "peekView.border": "#272727",
  "peekViewEditor.background": "#001f33",
  "peekViewEditor.matchHighlightBackground": "#ea762070",
  "peekViewEditor.matchHighlightBorder": "#d6d6d600",
  "peekViewEditorGutter.background": "#001f33",
  "peekViewResult.background": "#161616",
  "peekViewResult.fileForeground": "#d6d6d6",
  "peekViewResult.lineForeground": "#d6d6d6",
  "peekViewResult.matchHighlightBackground": "#ea762070",
  "peekViewResult.selectionBackground": "#363636",
  "peekViewResult.selectionForeground": "#d6d6d6",
  "peekViewTitle.background": "#161616",
  "peekViewTitleDescription.foreground": "#d6d6d6",
  "peekViewTitleLabel.foreground": "#d6d6d6",
  "pickerGroup.border": "#272727",
  "pickerGroup.foreground": "#d6d6d6",
  "progressBar.background": "#15ac91",
  "quickInput.foreground": "#b3b3b3",
  "scrollbar.shadow": "#d6d6d600",
  "scrollbarSlider.activeBackground": "#d6d6d619",
  "scrollbarSlider.background": "#d6d6d614",
  "scrollbarSlider.hoverBackground": "#d6d6d619",
  "selection.background": "#163761",
  "settings.focusedRowBackground": "#d6d6d607",
  "settings.headerForeground": "#d6d6d6",
  "settings.modifiedItemIndicator": "#efb080",
  "sideBar.background": "#0e0e0e",
  "sideBar.border": "#272727",
  "sideBar.dropBackground": "#d6d6d600",
  "sideBar.foreground": "#b3b3b3",
  "sideBarSectionHeader.background": "#13131300",
  "sideBarSectionHeader.border": "#272727",
  "sideBarSectionHeader.foreground": "#b3b3b3",
  "sideBarTitle.foreground": "#b3b3b3",
  "statusBar.background": "#0e0e0e",
  "statusBar.border": "#272727",
  "statusBar.debuggingBackground": "#efb080",
  "statusBar.debuggingForeground": "#0e0e0e",
  "statusBar.foreground": "#b3b3b3",
  "statusBar.noFolderBackground": "#0e0e0e",
  "statusBar.noFolderBorder": "#272727",
  "statusBar.noFolderForeground": "#b3b3b3",
  "statusBarItem.activeBackground": "#d6d6d625",
  "statusBarItem.hoverBackground": "#d6d6d620",
  "statusBarItem.remoteBackground": "#efb080",
  "statusBarItem.remoteForeground": "#0e0e0e",
  "statusBarItem.remoteHoverBackground": "#F2C19B",
  "statusBarItem.remoteHoverForeground": "#0e0e0e",
  "tab.activeBackground": "#131313",
  "tab.activeBorder": "#131313",
  "tab.activeBorderTop": "#d6d6d6",
  "tab.activeForeground": "#d6d6d6",
  "tab.border": "#292929",
  "tab.hoverBackground": "#101011",
  "tab.inactiveBackground": "#0e0e0e",
  "tab.inactiveForeground": "#999999",
  "tab.unfocusedActiveBorder": "#131313",
  "tab.unfocusedActiveBorderTop": "#131313",
  "tab.unfocusedHoverBackground": "#0e0e0e",
  "terminal.ansiBlack": "#676767",
  "terminal.ansiBlue": "#4c9df3",
  "terminal.ansiBrightBlack": "#676767",
  "terminal.ansiBrightBlue": "#4c9df3",
  "terminal.ansiBrightCyan": "#75d3ba",
  "terminal.ansiBrightGreen": "#15ac91",
  "terminal.ansiBrightMagenta": "#e567dc",
  "terminal.ansiBrightRed": "#f14c4c",
  "terminal.ansiBrightWhite": "#d6d6d6",
  "terminal.ansiBrightYellow": "#e5b95c",
  "terminal.ansiCyan": "#75d3ba",
  "terminal.ansiGreen": "#15ac91",
  "terminal.ansiMagenta": "#e567dc",
  "terminal.ansiRed": "#f14c4c",
  "terminal.ansiWhite": "#d6d6d6",
  "terminal.ansiYellow": "#e5b95c",
  "terminal.background": "#0e0e0e",
  "terminal.border": "#272727",
  "terminal.foreground": "#d6d6d6",
  "terminal.selectionBackground": "#d6d6d614",
  "terminalCursor.background": "#5b51ec",
  "terminalCursor.foreground": "#d6d6d6",
  "textLink.activeForeground": "#F2C19B",
  "textLink.foreground": "#efb080",
  "titleBar.activeBackground": "#0e0e0e",
  "titleBar.activeForeground": "#b3b3b3",
  "titleBar.border": "#272727",
  "titleBar.inactiveBackground": "#0e0e0e",
  "titleBar.inactiveForeground": "#b3b3b3",
  "tree.indentGuidesStroke": "#272727",
  "walkThrough.embeddedEditorBackground": "#00000050",
  "widget.border": "#272727",
  "widget.shadow": "#111111eb"
}

export const BLACKSPHERE_TOKEN_COLORS: VsCodeTokenColor[] = [
  { scope: "string.quoted.binary.single.python", settings: { foreground: "#A8CC7C" } },
  { scope: ["constant.language.false.cpp", "constant.language.true.cpp"], settings: { foreground: "#82D2CE" } },
  { scope: "punctuation.definition.delayed.unison,punctuation.definition.list.begin.unison,punctuation.definition.list.end.unison,punctuation.definition.ability.begin.unison,punctuation.definition.ability.end.unison,punctuation.operator.assignment.as.unison,punctuation.separator.pipe.unison,punctuation.separator.delimiter.unison,punctuation.definition.hash.unison", settings: { foreground: "#d6d6d6" } },
  { scope: "keyword.control.directive", settings: { foreground: "#A8CC7C" } },
  { scope: "constant.other.ellipsis.python", settings: { foreground: "#b3b3b3" } },
  { scope: "variable.other.generic-type.haskell", settings: { foreground: "#83D6C5" } },
  { scope: "punctuation.definition.tag", settings: { foreground: "#898989" } },
  { scope: "storage.type.haskell", settings: { foreground: "#F8C762" } },
  { scope: "support.variable.magic.python", settings: { foreground: "#d6d6d6" } },
  { scope: "punctuation.separator.period.python,punctuation.separator.element.python,punctuation.parenthesis.begin.python,punctuation.parenthesis.end.python", settings: { foreground: "#d6d6d6" } },
  { scope: "variable.parameter.function.language.special.self.python", settings: { foreground: "#efb080" } },
  { scope: "variable.language.this.cpp", settings: { foreground: "#82D2CE" } },
  { scope: "storage.modifier.lifetime.rust", settings: { foreground: "#d6d6d6" } },
  { scope: "support.function.std.rust", settings: { foreground: "#AAA0FA" } },
  { scope: "entity.name.lifetime.rust", settings: { foreground: "#efb080" } },
  { scope: "variable.other.property", settings: { foreground: "#AA9BF5" } },
  { scope: "variable.language.rust", settings: { foreground: "#d6d6d6" } },
  { scope: "support.constant.edge", settings: { foreground: "#83D6C5" } },
  { scope: "constant.other.character-class.regexp", settings: { foreground: "#d6d6d6" } },
  { scope: "keyword.operator.quantifier.regexp", settings: { foreground: "#F8C762" } },
  { scope: "punctuation.definition.string.begin,punctuation.definition.string.end", settings: { foreground: "#E394DC" } },
  { scope: "variable.parameter.function", settings: { foreground: "#d6d6d6" } },
  { scope: "comment markup.link", settings: { foreground: "#6D6D6D" } },
  { scope: "markup.changed.diff", settings: { foreground: "#efb080" } },
  { scope: "meta.diff.header.from-file,meta.diff.header.to-file,punctuation.definition.from-file.diff,punctuation.definition.to-file.diff", settings: { foreground: "#AAA0FA" } },
  { scope: "markup.inserted.diff", settings: { foreground: "#E394DC" } },
  { scope: "markup.deleted.diff", settings: { foreground: "#d6d6d6" } },
  { scope: "meta.function.c,meta.function.cpp", settings: { foreground: "#d6d6d6" } },
  { scope: "punctuation.section.block.begin.bracket.curly.cpp,punctuation.section.block.end.bracket.curly.cpp,punctuation.terminator.statement.c,punctuation.section.block.begin.bracket.curly.c,punctuation.section.block.end.bracket.curly.c,punctuation.section.parens.begin.bracket.round.c,punctuation.section.parens.end.bracket.round.c,punctuation.section.parameters.begin.bracket.round.c,punctuation.section.parameters.end.bracket.round.c", settings: { foreground: "#d6d6d6" } },
  { scope: "punctuation.separator.key-value", settings: { foreground: "#d6d6d6" } },
  { scope: "keyword.operator.expression.import", settings: { foreground: "#AAA0FA" } },
  { scope: "support.constant.math", settings: { foreground: "#efb080" } },
  { scope: "support.constant.property.math", settings: { foreground: "#F8C762" } },
  { scope: "variable.other.constant", settings: { foreground: "#AA9BF5" } },
  { scope: "variable.other.constant", settings: { foreground: "#AA9BF5" } },
  { scope: ["storage.type.annotation.java", "storage.type.object.array.java"], settings: { foreground: "#efb080" } },
  { scope: "source.java", settings: { foreground: "#d6d6d6" } },
  { scope: "punctuation.section.block.begin.java,punctuation.section.block.end.java,punctuation.definition.method-parameters.begin.java,punctuation.definition.method-parameters.end.java,meta.method.identifier.java,punctuation.section.method.begin.java,punctuation.section.method.end.java,punctuation.terminator.java,punctuation.section.class.begin.java,punctuation.section.class.end.java,punctuation.section.inner-class.begin.java,punctuation.section.inner-class.end.java,meta.method-call.java,punctuation.section.class.begin.bracket.curly.java,punctuation.section.class.end.bracket.curly.java,punctuation.section.method.begin.bracket.curly.java,punctuation.section.method.end.bracket.curly.java,punctuation.separator.period.java,punctuation.bracket.angle.java,punctuation.definition.annotation.java,meta.method.body.java", settings: { foreground: "#d6d6d6" } },
  { scope: "meta.method.java", settings: { foreground: "#AAA0FA" } },
  { scope: "storage.modifier.import.java,storage.type.java,storage.type.generic.java", settings: { foreground: "#efb080" } },
  { scope: "keyword.operator.instanceof.java", settings: { foreground: "#83D6C5" } },
  { scope: "meta.definition.variable.name.java", settings: { foreground: "#d6d6d6" } },
  { scope: "keyword.operator.logical", settings: { foreground: "#d6d6d6" } },
  { scope: "keyword.operator.bitwise", settings: { foreground: "#d6d6d6" } },
  { scope: "keyword.operator.channel", settings: { foreground: "#d6d6d6" } },
  { scope: "keyword.operator.css,keyword.operator.scss,keyword.operator.less", settings: { foreground: "#d6d6d6" } },
  { scope: "support.constant.color.w3c-standard-color-name.css,support.constant.color.w3c-standard-color-name.scss", settings: { foreground: "#F8C762" } },
  { scope: "punctuation.separator.list.comma.css", settings: { foreground: "#d6d6d6" } },
  { scope: "support.constant.color.w3c-standard-color-name.css", settings: { foreground: "#F8C762" } },
  { scope: "support.module.node,support.type.object.module,support.module.node", settings: { foreground: "#efb080" } },
  { scope: "entity.name.type.module", settings: { foreground: "#efb080" } },
  { scope: ",meta.object-literal.key,support.variable.object.process,support.variable.object.node", settings: { foreground: "#d6d6d6" } },
  { scope: "variable.other.readwrite", settings: { foreground: "#94C1FA" } },
  { scope: "support.variable.property", settings: { foreground: "#AA9BF5" } },
  { scope: "support.constant.json", settings: { foreground: "#F8C762" } },
  { scope: ["keyword.operator.expression.instanceof", "keyword.operator.new", "keyword.operator.ternary", "keyword.operator.optional", "keyword.operator.expression.keyof"], settings: { foreground: "#83D6C5" } },
  { scope: "support.type.object.console", settings: { foreground: "#d6d6d6" } },
  { scope: "support.variable.property.process", settings: { foreground: "#F8C762" } },
  { scope: "entity.name.function.js,support.function.console.js", settings: { foreground: "#EBC88D" } },
  { scope: "keyword.operator.misc.rust", settings: { foreground: "#d6d6d6" } },
  { scope: "keyword.operator.sigil.rust", settings: { foreground: "#83D6C5" } },
  { scope: "keyword.operator.delete", settings: { foreground: "#83D6C5" } },
  { scope: "support.type.object.dom", settings: { foreground: "#d6d6d6" } },
  { scope: "support.variable.dom,support.variable.property.dom", settings: { foreground: "#d6d6d6" } },
  { scope: "keyword.operator.arithmetic,keyword.operator.comparison,keyword.operator.decrement,keyword.operator.increment,keyword.operator.relational", settings: { foreground: "#d6d6d6" } },
  { scope: "keyword.operator.assignment.c,keyword.operator.comparison.c,keyword.operator.c,keyword.operator.increment.c,keyword.operator.decrement.c,keyword.operator.bitwise.shift.c,keyword.operator.assignment.cpp,keyword.operator.comparison.cpp,keyword.operator.cpp,keyword.operator.increment.cpp,keyword.operator.decrement.cpp,keyword.operator.bitwise.shift.cpp", settings: { foreground: "#83D6C5" } },
  { scope: "punctuation.separator.delimiter", settings: { foreground: "#d6d6d6" } },
  { scope: "punctuation.separator.c,punctuation.separator.cpp", settings: { foreground: "#83D6C5" } },
  { scope: "support.type.posix-reserved.c,support.type.posix-reserved.cpp", settings: { foreground: "#d6d6d6" } },
  { scope: "keyword.operator.sizeof.c,keyword.operator.sizeof.cpp", settings: { foreground: "#83D6C5" } },
  { scope: "variable.parameter.function.language.python", settings: { foreground: "#F8C762" } },
  { scope: "support.type.python", settings: { foreground: "#82D2CE" } },
  { scope: "keyword.operator.logical.python", settings: { foreground: "#83D6C5" } },
  { scope: "variable.parameter.function.python", settings: { foreground: "#F8C762" } },
  { scope: "punctuation.definition.arguments.begin.python,punctuation.definition.arguments.end.python,punctuation.separator.arguments.python,punctuation.definition.list.begin.python,punctuation.definition.list.end.python", settings: { foreground: "#d6d6d6" } },
  { scope: "meta.function-call.generic.python", settings: { foreground: "#AAA0FA" } },
  { scope: "constant.character.format.placeholder.other.python", settings: { foreground: "#F8C762" } },
  { scope: "keyword.operator", settings: { foreground: "#d6d6d6" } },
  { scope: "keyword.operator.assignment.compound", settings: { foreground: "#83D6C5" } },
  { scope: "keyword.operator.assignment.compound.js,keyword.operator.assignment.compound.ts", settings: { foreground: "#d6d6d6" } },
  { scope: "keyword", settings: { foreground: "#83D6C5" } },
  { scope: "entity.name.namespace", settings: { foreground: "#b3b3b3" } },
  { scope: "variable", settings: { foreground: "#d6d6d6" } },
  { scope: "variable.c", settings: { foreground: "#d6d6d6" } },
  { scope: "variable.language", settings: { foreground: "#C1808A" } },
  { scope: "token.variable.parameter.java", settings: { foreground: "#d6d6d6" } },
  { scope: "import.storage.java", settings: { foreground: "#efb080" } },
  { scope: "token.package.keyword", settings: { foreground: "#83D6C5" } },
  { scope: "token.package", settings: { foreground: "#d6d6d6" } },
  { scope: ["entity.name.function", "meta.require", "support.function", "variable.function"], settings: { foreground: "#efb080" } },
  { scope: "entity.name.type.namespace", settings: { foreground: "#efb080" } },
  { scope: "support.class, entity.name.type.class", settings: { foreground: "#87C3FF" } },
  { scope: "entity.name.class.identifier.namespace.type", settings: { foreground: "#efb080" } },
  { scope: ["entity.name.class", "variable.other.class.js", "variable.other.class.ts"], settings: { foreground: "#efb080" } },
  { scope: "variable.other.class.php", settings: { foreground: "#d6d6d6" } },
  { scope: "entity.name.type", settings: { foreground: "#efb080" } },
  { scope: "keyword.control.directive.include.cpp", settings: { foreground: "#A8CC7C" } },
  { scope: "control.elements, keyword.operator.less", settings: { foreground: "#F8C762" } },
  { scope: "keyword.other.special-method", settings: { foreground: "#AAA0FA" } },
  { scope: "storage", settings: { foreground: "#82D2CE" } },
  { scope: ["storage.modifier.reference", "storage.modifier.pointer"], settings: { foreground: "#b3b3b3" } },
  { scope: "token.storage", settings: { foreground: "#83D6C5" } },
  { scope: "keyword.operator.expression.delete,keyword.operator.expression.in,keyword.operator.expression.of,keyword.operator.expression.instanceof,keyword.operator.new,keyword.operator.expression.typeof,keyword.operator.expression.void", settings: { foreground: "#83D6C5" } },
  { scope: "token.storage.type.java", settings: { foreground: "#efb080" } },
  { scope: "support.function", settings: { foreground: "#efb080" } },
  { scope: "meta.property-name.css", settings: { foreground: "#87C3FF" } },
  { scope: "meta.tag", settings: { foreground: "#FAD075" } },
  { scope: "string", settings: { foreground: "#E394DC" } },
  { scope: "entity.other.inherited-class", settings: { foreground: "#efb080" } },
  { scope: "constant.other.symbol", settings: { foreground: "#d6d6d6" } },
  { scope: "constant.numeric", settings: { foreground: "#EBC88D" } },
  { scope: "constant.other.color", settings: { foreground: "#EBC88D" } },
  { scope: "punctuation.definition.constant", settings: { foreground: "#F8C762" } },
  { scope: ["entity.name.tag.template", "entity.name.tag.script", "entity.name.tag.style"], settings: { foreground: "#AF9CFF" } },
  { scope: ["entity.name.tag.html"], settings: { foreground: "#87C3FF" } },
  { scope: "meta.property-value.css", settings: { foreground: "#E394DC" } },
  { scope: "entity.other.attribute-name", settings: { foreground: "#AAA0FA" } },
  { scope: "entity.other.attribute-name.id", settings: { foreground: "#AAA0FA" } },
  { scope: "entity.other.attribute-name.class.css", settings: { foreground: "#F8C762" } },
  { scope: "meta.selector", settings: { foreground: "#83D6C5" } },
  { scope: "markup.heading", settings: { foreground: "#d6d6d6" } },
  { scope: "markup.heading punctuation.definition.heading, entity.name.section", settings: { foreground: "#AAA0FA" } },
  { scope: "keyword.other.unit", settings: { foreground: "#EBC88D" } },
  { scope: "markup.bold,todo.bold", settings: { foreground: "#F8C762" } },
  { scope: "punctuation.definition.bold", settings: { foreground: "#efb080" } },
  { scope: "markup.italic, punctuation.definition.italic,todo.emphasis", settings: { foreground: "#83D6C5" } },
  { scope: "emphasis md", settings: { foreground: "#83D6C5" } },
  { scope: "entity.name.section.markdown", settings: { foreground: "#d6d6d6" } },
  { scope: "punctuation.definition.heading.markdown", settings: { foreground: "#d6d6d6" } },
  { scope: "punctuation.definition.list.begin.markdown", settings: { foreground: "#d6d6d6" } },
  { scope: "markup.heading.setext", settings: { foreground: "#d6d6d6" } },
  { scope: "punctuation.definition.bold.markdown", settings: { foreground: "#F8C762" } },
  { scope: "markup.inline.raw.markdown", settings: { foreground: "#E394DC" } },
  { scope: "markup.inline.raw.string.markdown", settings: { foreground: "#E394DC" } },
  { scope: "punctuation.definition.list.markdown", settings: { foreground: "#d6d6d6" } },
  { scope: ["punctuation.definition.string.begin.markdown", "punctuation.definition.string.end.markdown", "punctuation.definition.metadata.markdown"], settings: { foreground: "#d6d6d6" } },
  { scope: ["beginning.punctuation.definition.list.markdown"], settings: { foreground: "#d6d6d6" } },
  { scope: "punctuation.definition.metadata.markdown", settings: { foreground: "#d6d6d6" } },
  { scope: "markup.underline.link.markdown,markup.underline.link.image.markdown", settings: { foreground: "#83D6C5" } },
  { scope: "string.other.link.title.markdown,string.other.link.description.markdown", settings: { foreground: "#AAA0FA" } },
  { scope: "string.regexp", settings: { foreground: "#d6d6d6" } },
  { scope: "constant.character.escape", settings: { foreground: "#d6d6d6" } },
  { scope: "punctuation.section.embedded, variable.interpolation", settings: { foreground: "#d6d6d6" } },
  { scope: "punctuation.section.embedded.begin,punctuation.section.embedded.end", settings: { foreground: "#83D6C5" } },
  { scope: "invalid.illegal", settings: { foreground: "#d6d6d6" } },
  { scope: "invalid.illegal.bad-ampersand.html", settings: { foreground: "#d6d6d6" } },
  { scope: "invalid.broken", settings: { foreground: "#d6d6d6" } },
  { scope: "invalid.deprecated", settings: { foreground: "#d6d6d6" } },
  { scope: "invalid.unimplemented", settings: { foreground: "#d6d6d6" } },
  { scope: "source.json meta.structure.dictionary.json > string.quoted.json", settings: { foreground: "#d6d6d6" } },
  { scope: "source.json meta.structure.dictionary.json > string.quoted.json > punctuation.string", settings: { foreground: "#d6d6d6" } },
  { scope: "source.json meta.structure.dictionary.json > value.json > string.quoted.json,source.json meta.structure.array.json > value.json > string.quoted.json,source.json meta.structure.dictionary.json > value.json > string.quoted.json > punctuation,source.json meta.structure.array.json > value.json > string.quoted.json > punctuation", settings: { foreground: "#E394DC" } },
  { scope: "source.json meta.structure.dictionary.json > constant.language.json,source.json meta.structure.array.json > constant.language.json", settings: { foreground: "#d6d6d6" } },
  { scope: "support.type.property-name.json", settings: { foreground: "#82D2CE" } },
  { scope: "text.html.laravel-blade source.php.embedded.line.html entity.name.tag.laravel-blade", settings: { foreground: "#83D6C5" } },
  { scope: "text.html.laravel-blade source.php.embedded.line.html support.constant.laravel-blade", settings: { foreground: "#83D6C5" } },
  { scope: "support.other.namespace.use.php,support.other.namespace.use-as.php,support.other.namespace.php,entity.other.alias.php,meta.interface.php", settings: { foreground: "#efb080" } },
  { scope: "keyword.operator.error-control.php", settings: { foreground: "#83D6C5" } },
  { scope: "keyword.operator.type.php", settings: { foreground: "#83D6C5" } },
  { scope: "punctuation.section.array.begin.php", settings: { foreground: "#d6d6d6" } },
  { scope: "punctuation.section.array.end.php", settings: { foreground: "#d6d6d6" } },
  { scope: "invalid.illegal.non-null-typehinted.php", settings: { foreground: "#F44747" } },
  { scope: "storage.type.php,meta.other.type.phpdoc.php,keyword.other.type.php,keyword.other.array.phpdoc.php", settings: { foreground: "#efb080" } },
  { scope: "meta.function-call.php,meta.function-call.object.php,meta.function-call.static.php", settings: { foreground: "#AAA0FA" } },
  { scope: "punctuation.definition.parameters.begin.bracket.round.php,punctuation.definition.parameters.end.bracket.round.php,punctuation.separator.delimiter.php,punctuation.section.scope.begin.php,punctuation.section.scope.end.php,punctuation.terminator.expression.php,punctuation.definition.arguments.begin.bracket.round.php,punctuation.definition.arguments.end.bracket.round.php,punctuation.definition.storage-type.begin.bracket.round.php,punctuation.definition.storage-type.end.bracket.round.php,punctuation.definition.array.begin.bracket.round.php,punctuation.definition.array.end.bracket.round.php,punctuation.definition.begin.bracket.round.php,punctuation.definition.end.bracket.round.php,punctuation.definition.begin.bracket.curly.php,punctuation.definition.end.bracket.curly.php,punctuation.definition.section.switch-block.end.bracket.curly.php,punctuation.definition.section.switch-block.start.bracket.curly.php,punctuation.definition.section.switch-block.begin.bracket.curly.php,punctuation.definition.section.switch-block.end.bracket.curly.php", settings: { foreground: "#d6d6d6" } },
  { scope: "support.constant.core.rust", settings: { foreground: "#F8C762" } },
  { scope: "support.constant.ext.php,support.constant.std.php,support.constant.core.php,support.constant.parser-token.php", settings: { foreground: "#F8C762" } },
  { scope: "entity.name.goto-label.php,support.other.php", settings: { foreground: "#AAA0FA" } },
  { scope: "keyword.operator.logical.php,keyword.operator.bitwise.php,keyword.operator.arithmetic.php", settings: { foreground: "#d6d6d6" } },
  { scope: "keyword.operator.regexp.php", settings: { foreground: "#83D6C5" } },
  { scope: "keyword.operator.comparison.php", settings: { foreground: "#d6d6d6" } },
  { scope: "keyword.operator.heredoc.php,keyword.operator.nowdoc.php", settings: { foreground: "#83D6C5" } },
  { scope: "meta.function.decorator.python", settings: { foreground: "#A8CC7C" } },
  { scope: "punctuation.definition.decorator.python,entity.name.function.decorator.python", settings: { foreground: "#A8CC7C" } },
  { scope: "support.token.decorator.python,meta.function.decorator.identifier.python", settings: { foreground: "#d6d6d6" } },
  { scope: "function.parameter", settings: { foreground: "#d6d6d6" } },
  { scope: "function.brace", settings: { foreground: "#d6d6d6" } },
  { scope: "function.parameter.ruby, function.parameter.cs", settings: { foreground: "#d6d6d6" } },
  { scope: "constant.language.symbol.ruby", settings: { foreground: "#d6d6d6" } },
  { scope: "rgb-value", settings: { foreground: "#d6d6d6" } },
  { scope: "inline-color-decoration rgb-value", settings: { foreground: "#F8C762" } },
  { scope: "less rgb-value", settings: { foreground: "#F8C762" } },
  { scope: "selector.sass", settings: { foreground: "#d6d6d6" } },
  { scope: "support.type.primitive.ts,support.type.builtin.ts,support.type.primitive.tsx,support.type.builtin.tsx", settings: { foreground: "#82D2CE" } },
  { scope: "block.scope.end,block.scope.begin", settings: { foreground: "#d6d6d6" } },
  { scope: "storage.type.cs", settings: { foreground: "#efb080" } },
  { scope: "entity.name.variable.local.cs", settings: { foreground: "#d6d6d6" } },
  { scope: "token.info-token", settings: { foreground: "#AAA0FA" } },
  { scope: "token.warn-token", settings: { foreground: "#F8C762" } },
  { scope: "token.error-token", settings: { foreground: "#F44747" } },
  { scope: "token.debug-token", settings: { foreground: "#83D6C5" } },
  { scope: ["punctuation.definition.template-expression.begin", "punctuation.definition.template-expression.end", "punctuation.section.embedded"], settings: { foreground: "#83D6C5" } },
  { scope: ["meta.template.expression"], settings: { foreground: "#d6d6d6" } },
  { scope: ["keyword.operator.module"], settings: { foreground: "#83D6C5" } },
  { scope: ["support.type.type.flowtype"], settings: { foreground: "#AAA0FA" } },
  { scope: ["support.type.primitive"], settings: { foreground: "#efb080" } },
  { scope: ["meta.property.object"], settings: { foreground: "#d6d6d6" } },
  { scope: ["variable.parameter.function.js"], settings: { foreground: "#d6d6d6" } },
  { scope: ["keyword.other.template.begin"], settings: { foreground: "#E394DC" } },
  { scope: ["keyword.other.template.end"], settings: { foreground: "#E394DC" } },
  { scope: ["keyword.other.substitution.begin"], settings: { foreground: "#E394DC" } },
  { scope: ["keyword.other.substitution.end"], settings: { foreground: "#E394DC" } },
  { scope: ["keyword.operator.assignment"], settings: { foreground: "#d6d6d6" } },
  { scope: ["keyword.operator.assignment.go"], settings: { foreground: "#efb080" } },
  { scope: ["keyword.operator.arithmetic.go", "keyword.operator.address.go"], settings: { foreground: "#83D6C5" } },
  { scope: ["entity.name.package.go"], settings: { foreground: "#efb080" } },
  { scope: ["support.type.prelude.elm"], settings: { foreground: "#d6d6d6" } },
  { scope: ["support.constant.elm"], settings: { foreground: "#F8C762" } },
  { scope: ["punctuation.quasi.element"], settings: { foreground: "#83D6C5" } },
  { scope: ["constant.character.entity"], settings: { foreground: "#d6d6d6" } },
  { scope: ["entity.other.attribute-name.pseudo-element", "entity.other.attribute-name.pseudo-class"], settings: { foreground: "#d6d6d6" } },
  { scope: ["entity.global.clojure"], settings: { foreground: "#efb080" } },
  { scope: ["meta.symbol.clojure"], settings: { foreground: "#d6d6d6" } },
  { scope: ["constant.keyword.clojure"], settings: { foreground: "#d6d6d6" } },
  { scope: ["meta.arguments.coffee", "variable.parameter.function.coffee"], settings: { foreground: "#d6d6d6" } },
  { scope: ["source.ini"], settings: { foreground: "#E394DC" } },
  { scope: ["meta.scope.prerequisites.makefile"], settings: { foreground: "#d6d6d6" } },
  { scope: ["source.makefile"], settings: { foreground: "#efb080" } },
  { scope: ["storage.modifier.import.groovy"], settings: { foreground: "#efb080" } },
  { scope: ["meta.method.groovy"], settings: { foreground: "#AAA0FA" } },
  { scope: ["meta.definition.variable.name.groovy"], settings: { foreground: "#d6d6d6" } },
  { scope: ["meta.definition.class.inherited.classes.groovy"], settings: { foreground: "#E394DC" } },
  { scope: ["support.variable.semantic.hlsl"], settings: { foreground: "#efb080" } },
  { scope: ["support.type.texture.hlsl", "support.type.sampler.hlsl", "support.type.object.hlsl", "support.type.object.rw.hlsl", "support.type.fx.hlsl", "support.type.object.hlsl"], settings: { foreground: "#83D6C5" } },
  { scope: ["text.variable", "text.bracketed"], settings: { foreground: "#d6d6d6" } },
  { scope: ["support.type.swift", "support.type.vb.asp"], settings: { foreground: "#efb080" } },
  { scope: ["entity.name.function.xi"], settings: { foreground: "#efb080" } },
  { scope: ["entity.name.class.xi"], settings: { foreground: "#d6d6d6" } },
  { scope: ["constant.character.character-class.regexp.xi"], settings: { foreground: "#d6d6d6" } },
  { scope: ["constant.regexp.xi"], settings: { foreground: "#83D6C5" } },
  { scope: ["keyword.control.xi"], settings: { foreground: "#d6d6d6" } },
  { scope: ["invalid.xi"], settings: { foreground: "#d6d6d6" } },
  { scope: ["beginning.punctuation.definition.quote.markdown.xi"], settings: { foreground: "#E394DC" } },
  { scope: ["beginning.punctuation.definition.list.markdown.xi"], settings: { foreground: "#6D6D6D" } },
  { scope: ["constant.character.xi"], settings: { foreground: "#AAA0FA" } },
  { scope: ["accent.xi"], settings: { foreground: "#AAA0FA" } },
  { scope: ["wikiword.xi"], settings: { foreground: "#F8C762" } },
  { scope: ["constant.other.color.rgb-value.xi"], settings: { foreground: "#d6d6d6" } },
  { scope: ["punctuation.definition.tag.xi"], settings: { foreground: "#6D6D6D" } },
  { scope: ["entity.name.label.cs", "entity.name.scope-resolution.function.call", "entity.name.scope-resolution.function.definition"], settings: { foreground: "#efb080" } },
  { scope: ["entity.name.label.cs", "markup.heading.setext.1.markdown", "markup.heading.setext.2.markdown"], settings: { foreground: "#d6d6d6" } },
  { scope: [" meta.brace.square"], settings: { foreground: "#d6d6d6" } },
  { scope: "comment, punctuation.definition.comment", settings: { foreground: "#6D6D6D", fontStyle: "italic" } },
  { scope: "markup.quote.markdown", settings: { foreground: "#6D6D6D" } },
  { scope: "punctuation.definition.block.sequence.item.yaml", settings: { foreground: "#d6d6d6" } },
  { scope: ["constant.language.symbol.elixir"], settings: { foreground: "#d6d6d6" } },
  { scope: "entity.other.attribute-name.js,entity.other.attribute-name.ts,entity.other.attribute-name.jsx,entity.other.attribute-name.tsx,variable.parameter,variable.language.super", settings: { fontStyle: "italic" } },
  { scope: "comment.line.double-slash,comment.block.documentation", settings: { fontStyle: "italic" } },
  { scope: "keyword.control.import.python,keyword.control.flow.python", settings: { fontStyle: "italic" } },
  { scope: "markup.italic.markdown", settings: { fontStyle: "italic" } }
]

export function cssVarName(vscodeKey: string): string {
  return `--vscode-${vscodeKey.replace(/\./g, '-')}`
}

export function applyVsCodeColors(colors: VsCodeThemeColors): void {
  const root = document.documentElement
  for (const [key, value] of Object.entries(colors)) {
    root.style.setProperty(cssVarName(key), value)
  }
}

export function clearVsCodeColors(): void {
  const root = document.documentElement
  for (const key of Object.keys(BLACKSPHERE_COLORS)) {
    root.style.removeProperty(cssVarName(key))
  }
}

export function injectTokenColors(tokenColors: VsCodeTokenColor[]): void {
  let style = document.getElementById('vscode-token-colors') as HTMLStyleElement | null
  if (!style) {
    style = document.createElement('style')
    style.id = 'vscode-token-colors'
    document.head.appendChild(style)
  }
  const rules = tokenColors.map((tc) => {
    const scopes = Array.isArray(tc.scope) ? tc.scope.join(', ') : tc.scope
    const fg = tc.settings.foreground ? `color: ${tc.settings.foreground} !important;` : ''
    const bg = tc.settings.background ? `background: ${tc.settings.background} !important;` : ''
    const fs = tc.settings.fontStyle ? `font-style: ${tc.settings.fontStyle.includes('italic') ? 'italic' : 'normal'}; font-weight: ${tc.settings.fontStyle.includes('bold') ? 'bold' : 'normal'}; ${tc.settings.fontStyle.includes('underline') ? 'text-decoration: underline;' : ''}` : ''
    if (!fg && !bg && !fs) return ''
    return `/* ${scopes} */ .hljs-keyword, .hljs-string, .hljs-comment, .chat-markdown code { ${fg} ${bg} ${fs} }`
  }).join('\n')
  const syntaxVars = `
    :root {
      --syntax-string: ${tokenColors.find(c => c.scope === 'string')?.settings.foreground ?? '#E394DC'};
      --syntax-keyword: #83D6C5;
      --syntax-comment: #6D6D6D;
      --syntax-variable: #d6d6d6;
      --syntax-function: #efb080;
      --syntax-type: #87C3FF;
      --syntax-number: #EBC88D;
    }
  `
  style.textContent = syntaxVars + '\n' + rules
}

export function clearTokenColors(): void {
  const style = document.getElementById('vscode-token-colors')
  if (style) style.remove()
}
