FROM node@sha256:be23f54a88d34e8824c741b19b91064094f92c1c97b194144bfc8b50d67258e2
RUN apt-get update && apt-get install -y --no-install-recommends libgtk-3-0 libnss3 libasound2 libgbm1 libxss1 libsecret-1-0 gnome-keyring dbus-x11 xvfb libdrm2 libxshmfence1 libxkbcommon0 libxrandr2 libcups2 fonts-liberation unzip && rm -rf /var/lib/apt/lists/*
