#!/usr/bin/env node
import { spawn } from 'node:child_process'
import { createHash,randomUUID,randomBytes } from 'node:crypto'
import { mkdirSync,readFileSync,writeFileSync,existsSync,readdirSync } from 'node:fs'
import { resolve,join } from 'node:path'
import { DatabaseSync } from 'node:sqlite'
const executable=resolve(process.env.MOUSSE_LINUX_PACKAGE_EXECUTABLE??'.mousse-dev/net-packaging/linux/package-final/linux-arm64-unpacked/mousse-cli'), asar=join(executable,'../resources/app.asar')
const root='/tmp/mousse-linux-production', output=resolve('.mousse-dev/net-packaging/linux/evidence');mkdirSync(root,{recursive:true,mode:0o700});mkdirSync(output,{recursive:true})
const sha=file=>createHash('sha256').update(readFileSync(file)).digest('hex'), hashes={asar:sha(asar),executable:sha(executable)}, env={...process.env,ELECTRON_DISABLE_SANDBOX:'1',NO_COLOR:'1',MOUSSE_REPO_ROOT:root};delete env.ELECTRON_RUN_AS_NODE
const report={v:1,source:process.env.MOUSSE_QA_SOURCE_SHA??'unspecified',hostNode:process.version,platform:process.platform,arch:process.arch,hashes,driver:sha(new URL(import.meta.url)),productionMain:'out/main/cli.js',sandbox:'root ELECTRON_DISABLE_SANDBOX=1 in isolated container',providersActivated:false,steps:[],cleanup:[]}, children=new Set(),daemons=new Map(),profiles=['a','b','c','d'],home=i=>join(root,profiles[i]); let error
const passphrase=randomBytes(32).toString('base64url')
function check(value,message){if(!value)throw Error(message)}
function sql(i,query){const installation=JSON.parse(readFileSync(join(home(i),'installation.json'),'utf8')),db=new DatabaseSync(join(home(i),'profiles',installation.defaultProfileId,'net/net.db'),{readOnly:true});try{return db.prepare(query).all()}finally{db.close()}}
const originals=i=>shaBytes(JSON.stringify(sql(i,'SELECT id,stream,envelope,sig,state,attempts,epoch,seq FROM net_outbox ORDER BY rowid')))
const shaBytes=bytes=>createHash('sha256').update(bytes).digest('hex')
async function denied(i,args){const r=await run(i,args);report.denials??=[];report.denials.push({command:args.slice(0,2).join(' '),actualExitCode:r.code,expectedExitCode:130,body:r.data??null,stdoutEmpty:r.stdout.length===0});save();check(r.code===130&&r.data?.code==='cancelled','Disabled admission exit/body did not preserve cancelled');report.steps.push({profile:profiles[i],command:args.slice(0,2).join(' '),denied:'cancelled'});save()}
async function attach(i,node,thread){return new Promise((res,rej)=>{const child=own(spawn(executable,['--home',home(i),'--json','bridge','attach',node,thread],{env:{...env,MOUSSE_HOME:home(i)},stdio:['ignore','pipe','pipe']}));let out='',err='',view,signalled=false;const timer=setTimeout(()=>{child.kill('SIGKILL');rej(Error('Bridge snapshot deadline'))},20000);child.stdout.on('data',b=>{out+=b;try{view=JSON.parse(out);if(view.kind==='snapshot'&&!signalled){signalled=true;child.kill('SIGINT')}}catch{}});child.stderr.on('data',b=>err=(err+b).slice(-4000));child.once('exit',code=>{clearTimeout(timer);if(code!==0||!view||!signalled)rej(Error('Bridge display did not complete: '+err));else res({kind:view.kind,sha256:shaBytes(out),bytes:Buffer.byteLength(out),nameVerified:out.includes('Linux packaged original')})});child.once('error',rej)})}
function save(){writeFileSync(join(output,'production.json'),JSON.stringify(report,null,2)+'\n')}
const delay=ms=>new Promise(r=>setTimeout(r,ms))
async function until(fn,predicate,timeout=20000){const end=Date.now()+timeout;do{const value=await fn();if(predicate(value))return value;await delay(100)}while(Date.now()<end);throw Error('Bounded readiness deadline')}
function own(child){children.add(child);child.once('exit',()=>children.delete(child));return child}
function run(i,args,input){return new Promise((res,rej)=>{if(sha(asar)!==hashes.asar||sha(executable)!==hashes.executable)throw Error('Immutable package changed');const child=own(spawn(executable,['--home',home(i),'--json',...args],{env:{...env,MOUSSE_HOME:home(i)},stdio:['pipe','pipe','pipe']}));let stdout='',stderr='';const timeout=setTimeout(()=>{child.kill('SIGKILL');rej(Error('CLI deadline: '+args.slice(0,2).join(' ')))},20000);child.stdout.on('data',b=>{stdout+=b;if(stdout.length>4*1024*1024)child.kill('SIGKILL')});child.stderr.on('data',b=>stderr=(stderr+b).slice(-12000));child.once('error',rej);child.once('exit',(code,signal)=>{clearTimeout(timeout);let data;try{data=JSON.parse(stdout.trim()||stderr.trim().split('\n').findLast(s=>s.startsWith('{')))}catch{};res({code,signal,data,stderr,stdout})});child.stdin.end(input)})}
async function ok(i,args,input){const r=await run(i,args,input);if(r.code!==0||!r.data)throw Error('CLI '+args.slice(0,2).join(' ')+': '+r.stderr);report.steps.push({profile:profiles[i],command:args.slice(0,2).join(' '),ok:true});save();return r.data}
async function launch(i){const child=own(spawn(executable,['--home',home(i),'service','run'],{env:{...env,MOUSSE_HOME:home(i)},stdio:['ignore','pipe','pipe']}));let log='';child.stdout.on('data',b=>log=(log+b).slice(-16000));child.stderr.on('data',b=>log=(log+b).slice(-16000));daemons.set(i,child);try{await until(()=>{if(child.exitCode!==null||child.signalCode!==null)throw Error('Production daemon exited: '+log);try{return JSON.parse(readFileSync(join(home(i),'mms.runtime.json'),'utf8')).pid===child.pid}catch{return false}},Boolean,25000)}catch(e){writeFileSync(join(output,'daemon-'+profiles[i]+'.log'),log);throw e}return child}
async function stop(child){if(child.exitCode!==null||child.signalCode!==null)return;const pid=child.pid,ended=new Promise(r=>child.once('exit',()=>r()));child.kill('SIGTERM');let forced=false;const timer=setTimeout(()=>{forced=true;child.kill('SIGKILL')},5000);await ended;clearTimeout(timer);report.cleanup.push({pid,forced,code:child.exitCode,signal:child.signalCode})}
try{
 const version=await new Promise((res,rej)=>{const child=own(spawn(executable,['--version'],{env}));let out='';child.stdout.on('data',b=>out+=b);child.stderr.on('data',()=>{});child.once('exit',code=>code===0?res(out.trim()):rej(Error('Actual package version failed')))});report.version=version
 const help=await run(0,['--help']);check(help.code===0&&help.stdout.includes('Usage'),'Actual packaged help failed');for(const args of [['bridge','rename'],['net','unknown-local-command']]){const invalid=await run(0,args);check(invalid.code!==0&&invalid.data?.code==='bad_request','Missing/unknown packaged command did not exit nonzero');report.steps.push({command:args.join(' '),actualExitCode:invalid.code,error:invalid.data.code})}
 await launch(0);const initial=await ok(0,['net','status']);report.initial=initial;await ok(0,['net','init','--listen','--port','0','--name','linux-package-authority']);report.initialized=await ok(0,['net','status']);

 check(initial.enabled===false&&initial.features.netBridge===false&&initial.features.netSpaces===false,'Fresh defaults enabled Net')
 await ok(0,['net','protect'],passphrase);const authority=await ok(0,['net','status']);check(authority.protected===true,'Authority keys not protected');report.authority={node:authority.self.node,user:authority.self.user,protected:authority.protected}
 await launch(1);const invitation=await ok(0,['bridge','invite']);await ok(1,['bridge','join'],invitation.invite+'\n');await ok(1,['net','protect'],passphrase);const member=await ok(1,['net','status']);check(member.protected&&member.self.user===authority.self.user&&member.self.node!==authority.self.node,'Enrollment identity/pin mismatch');await until(()=>ok(1,['net','status']),s=>s.peers.some(p=>p.node===authority.self.node&&p.state==='open'));report.enrollment={sameUser:true,distinctNode:true,protected:true}
 const id='rpc_'+randomBytes(13).toString('hex'),args=['bridge','create',authority.self.node,'Linux packaged original','--id',id,'--idem','linux-package-original'];const created=await ok(1,args);check(created.id===id&&created.result?.thread?.id,'Original RPC identity absent');const thread=created.result.thread.id,again=await ok(1,args);check(JSON.stringify(again)===JSON.stringify(created),'Original RPC retry changed result');const result=await ok(1,['bridge','result',id]);check(JSON.stringify(result)===JSON.stringify(created.result),'Original result lookup changed');const listed=await ok(1,['bridge','threads',authority.self.node]),got=await ok(1,['bridge','get',authority.self.node,thread]);check(JSON.stringify(listed).includes(thread)&&JSON.stringify(got).includes('Linux packaged original'),'Bridge list/get did not read original');const mutations=sql(0,"SELECT DISTINCT execution FROM net_rpc_aliases WHERE method='threads.create'");check(mutations.length===1,'Bridge original executed more than once');report.bridge={id,thread,executionCount:mutations.length,display:await attach(1,authority.self.node,thread)}
 await ok(1,['net','disable']);await denied(1,['bridge','threads',authority.self.node]);await stop(daemons.get(1));
 // A, C and D have independent Roots; B is the same-user Bridge enrollee only.
 const statuses=[authority];for(const i of [2,3]){await launch(i);await ok(i,['net','init','--listen','--port','0']);await ok(i,['net','protect'],passphrase);statuses.push(await ok(i,['net','status']))}check(new Set(statuses.map(s=>s.self.user)).size===3,'Public Space authors are not independent identities')
 const space=await ok(0,['spaces','create','Linux production ASAR Space']);for(const i of [2,3]){const invite=await ok(0,['spaces','invite',space.space]);await ok(i,['spaces','join'],invite.invite+'\n')}
 const expected=[];for(const i of [0,2,3]){const text='linux-asar-original-'+profiles[i]+'-'+randomUUID(),receipt=await ok(i,['spaces','post',space.channel,text]);check(receipt.state==='sent'&&receipt.position?.epoch===1,'Actual original did not reach sent');expected.push({i,text,receipt})}
 for(const i of [0,2,3]){const page=await until(()=>ok(i,['spaces','tail',space.channel]),p=>p.records?.length===3);check(page.records.every((r,index)=>{const e=expected[index],s=statuses[[0,2,3].indexOf(e.i)];return r.envelope.id===e.receipt.id&&r.envelope.body.text===e.text&&r.envelope.author.user===s.self.user&&r.envelope.author.node===s.self.node&&r.seq===e.receipt.position.seq&&r.epoch===e.receipt.position.epoch}),'Replicated signed original identity/order mismatch')}
 const before=originals(2),disabled=await ok(2,['net','disable']);check(!disabled.enabled&&disabled.restartRequired&&disabled.routes.length===0,'Rollback did not close routes');await denied(2,['spaces','post',space.channel,'denied original']);await denied(2,['net','init']);check(originals(2)===before,'Rollback changed original outbox bytes');await stop(daemons.get(2));await launch(2);const restarted=await ok(2,['net','status']);check(!restarted.enabled&&restarted.features.netBridge===false&&restarted.features.netSpaces===false&&restarted.routes.length===0,'Restart silently enabled profile');await ok(2,['net','unlock'],passphrase);await denied(2,['spaces','list']);check(originals(2)===before,'Disabled restart changed original bytes');await ok(2,['net','init']);await until(()=>ok(2,['spaces','tail',space.channel]),p=>p.records?.length===3);check(originals(2)===before,'Explicit opt-in rewrote original outbox');
 report.spaces={space:space.space,stream:space.channel,independentUsers:3,replicas:3,originals:expected.map(e=>({id:e.receipt.id,position:e.receipt.position})),rollback:{persistedOff:true,restartOff:true,explicitOptIn:true,outboxOriginalSha256:before,originalBytesRetained:true}}
 report.status='passed';report.exitStatusQualified=report.denials.every(d=>d.actualExitCode===d.expectedExitCode);

}catch(e){error=e;report.status='failed';report.error=String(e)}finally{for(const child of [...children].reverse())await stop(child);report.remainingOwnedChildren=children.size;report.remainingOwnedProcesses=readdirSync('/proc').filter(p=>/^\d+$/.test(p)).filter(p=>{try{const argv=readFileSync('/proc/'+p+'/cmdline','utf8');return argv.includes(executable)}catch{return false}});save()}
console.log(JSON.stringify({status:report.status,version:report.version,steps:report.steps.length,error:report.error,cleanup:report.cleanup,remainingOwnedChildren:children.size}));if(error)process.exitCode=1
