/** Bounded v1 workflow format limits. Oversized graphs/schemas fail compilation. */

export const WORKFLOW_FORMAT_SCHEMA_VERSION = 1

export const WORKFLOW_SLUG_MAX_LENGTH = 64
export const WORKFLOW_NAME_MAX_LENGTH = 120
export const WORKFLOW_DESCRIPTION_MAX_LENGTH = 2000
export const WORKFLOW_ID_MAX_LENGTH = 36

export const WORKFLOW_MAX_NODES = 250
export const WORKFLOW_MAX_EDGES = 1000
export const WORKFLOW_MAX_NESTING_DEPTH = 8
export const WORKFLOW_MAX_SUBWORKFLOW_DEPTH = 8
export const WORKFLOW_MAX_MANIFEST_BYTES = 1_000_000
export const WORKFLOW_MAX_ASSET_BYTES = 2_000_000
export const WORKFLOW_MAX_BUNDLE_BYTES = 5_000_000
export const WORKFLOW_MAX_ASSET_COUNT = 64
export const WORKFLOW_MAX_SCHEMA_DEPTH = 8
export const WORKFLOW_MAX_SCHEMA_PROPERTIES = 64
export const WORKFLOW_MAX_SCHEMA_ENUM = 64
export const WORKFLOW_MAX_SCHEMA_DEFS = 32
export const WORKFLOW_MAX_STRING_LENGTH = 200_000
export const WORKFLOW_MAX_BINDING_DEPTH = 12
export const WORKFLOW_MAX_EXPRESSION_DEPTH = 12
export const WORKFLOW_MAX_EXPRESSION_ARGS = 8
export const WORKFLOW_MAX_ARRAY_ITEMS = 1000
export const WORKFLOW_MAX_LOOP_ITERATIONS = 500
export const WORKFLOW_MAX_PARALLEL_BRANCHES = 16
export const WORKFLOW_MAX_SWITCH_CASES = 32
export const WORKFLOW_MAX_JSON_POINTER_LENGTH = 256
export const WORKFLOW_MAX_RELATIVE_PATH_LENGTH = 240
export const WORKFLOW_MAX_PATH_COMPONENT_LENGTH = 128
export const WORKFLOW_MAX_PATH_DEPTH = 12
export const WORKFLOW_MAX_IMPORT_ENTRIES = 200
export const WORKFLOW_MAX_COMPRESSION_RATIO = 100
export const WORKFLOW_MAX_RETRY_ATTEMPTS = 8
export const WORKFLOW_DEFAULT_MAX_CONCURRENCY = 4

export const WORKFLOW_SLUG_PATTERN = /^[a-z0-9][a-z0-9_-]{0,63}$/
export const WORKFLOW_UUID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
